### PR TITLE
Improve editor support

### PR DESCRIPTION
**Pull request by crocket**
I tested it with emacs(client), nano, vscode, kakoune, nvim, and vis.

### CODE REVIEW

**Comment by simonmichael** [comment]
Thanks! Could you make it the reason for the change a bit clearer in the commit message ? I'm not sure what it is.

**Comment by crocket** [comment]
I just made the commit message more precise.

**Comment by simonmichael** [comment]
The message looks quite informative now, but I'm still unclear -

> Documentation for editFileAtPositionCommand is made more
> precise.

Sounds good!

> This commit makes hledger-ui open an editor at the last line
> if the editor supports opening a file at the last line.
>
> It also makes hledger-ui open an editor without any argument
> if no information about cursor position is given.

I thought it did both of those already, did you find a problem ?

> In other words, editFileAtPositionCommand is made to behave
> with more precision.

What will we need to tell users in the release notes ?

> I tested it with emacs(client), nano, vscode, kakoune,
> nvim, and vis.

Excellent.

**Comment by crocket** [comment]
> I thought it did both of those already, did you find a problem ?

`editFileAtPositionCommand` used to give `+` as an argument to editors.
It wasn't precise with arguments it passed to editors.

**Comment by crocket** [comment]
I just improved commit message. Can you check it again?

**Comment by simonmichael** [comment]
Looks great, thanks a lot!

**Pull request merged**
