### PR TITLE
hledger-web: Set default javascript parameter values in the functions addformReset, addFormShow

### PR DESCRIPTION
**Pull request by kmels**
http://demo.hledger.org/journal gives some javascript errors, these prevent showing the nice chart and kb shortcuts from working

### CODE REVIEW

**Comment by simonmichael** [comment]
Thanks!

I don't see the error in firefox. What's your browser version ?

**Comment by kmels** [comment]
Hey, my version is chrome 41.0.2272.118
I can see the chart fine in Firefox too..  [it seems like this feature is only supported by Firefox at the moment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Browser_compatibility)

**Comment by simonmichael** [comment]
Ack - thanks!

**Comment by simonmichael** [comment]
Hi Carlos, this breaks the add form in my firefox: ReferenceError: a is not defined 141:12. Can you fix ?

**Comment by simonmichael** [comment]
PS only when you press the `a` key. It works when you click add a transaction. (Which is odd, why doesn't the latter go through the same code path).

**Comment by kmels** [comment]
Hi Simon! Omg, I don't know why I put there this letter. I am fixing it.

**Pull request merged**
