### PR TITLE
Support custom separators in CSV Import

### PR DESCRIPTION
**Pull request by lucamolteni**
Changed the CSV parser from Text.CSV to cassava-megaparsec

use the `--separator` parameter (default to ,)

there's a new test in the func suite using the semicolon ;

### CODE REVIEW

**Comment by lucamolteni** [comment]
Ok I already saw there a few warnings, I'm going to fix them

**Comment by simonmichael** [comment]
Hi @lucamolteni, any work planned on this ? Can we help with anything ?

**Comment by lucamolteni** [comment]
Sorry @simonmichael I was on vacation - I'm working on it this week

**Comment by lucamolteni** [comment]
I've fixed some of the warnings. How do I get the full list?

I tried with 

`stack build --ghc-options="-Wall -Werror"`

But it seems a bit too much (it shows error from parts I haven't touched)

**Comment by simonmichael** [comment]
@lucamolteni I usually see warnings from `make ghcid`. More thorough is `make buildtest` (finds warnings in all build targets, with current GHC) or if you have a lot of time and space `make buildtestall` (tests with all supported GHCs). `make buildtests` is passing in current master.

**Comment by simonmichael** [comment]
(https://github.com/simonmichael/hledger/wiki/Tests updated.)

**Comment by lucamolteni** [comment]
@simonmichael I can see why the "needs:docs" tag, but as for the test, don't you think the test I added is enough?

**Comment by simonmichael** [comment]
It sounded like you were still testing/fixing build warnings, that's what I meant.

**Comment by simonmichael** [comment]
Hi @lucamolteni, I'm pinging you so I don't forget this PR. I think you are still working on this. Or, if you're finished/stopped and have uploaded latest code for review/help, let me know.

**Comment by lucamolteni** [comment]
@simonmichael fixed conflicts

**Comment by simonmichael** [comment]
This has been merged, with some fixups and the flag added to docs. Thanks a lot!

**Comment by Pastafarianist** [comment]
Perhaps a better place to configure the separator character is the `.rules` file, not a command-line argument?

**Comment by schoettl** [comment]
There is already a issue for that #868

**Pull request closed without merging**
