### PR TITLE
Update achievements listing

### PR DESCRIPTION
**Pull request by alhirzel**
noticed these when digging thru the docs!

### CODE REVIEW

**Comment by simonmichael** [comment]
Thanks! Got a link for the "in top 30 github starred haskell projects" ?

**Comment by simonmichael** [comment]
(Reckoning by http://stars.hledger.org we are still at #35.)

**Comment by alhirzel** [comment]
I just manually counted down this list, looks like number 23: https://github.com/topics/haskell?o=desc&s=stars

Do you prefer to use the link you posted? If so I'll modify the PR. Thanks for the detailed check, I'd hate to get this wrong!

**Comment by alhirzel** [comment]
And note that it's number 17 on this list, which filters the last link I posted to projects that indicate their language is Haskell AND are tagged as #haskell. https://github.com/topics/haskell?l=haskell&o=desc&s=stars

**Comment by simonmichael** [comment]
It's not a big deal but yes I think the http://stars.hledger.org list is best (I've now trimmed it to >2k stars, making it shorter). Because the others find only the projects who have somehow configured (?) their topic; ours seems more accurate, eg it includes https://github.com/github/semantic, and excludes https://github.com/hmemcpy/milewski-ctfp-pdf.

**Comment by alhirzel** [comment]
@simonmichael - understood and updated PR to only take credit for the 2000 stars

**Pull request merged**
