### PR TITLE
;imp: added systemd and nginx files to examples dir

### PR DESCRIPTION
**Pull request by harleypig**
This commit contains example files for a hledger-web systemd service and the basics for an nginx reverse proxy.

### CODE REVIEW

**Comment by simonmichael** [comment]
Thanks! This is the first PR to which we'll apply the [new commit conventions scheme](https://hledger.org/CONTRIBUTING.html#commit-messages). Would you mind just adding a prefix to the commit message, oh let's say `;imp: doc: ` ("a user-visible improvement in the area of documentation, don't bother with CI").

I'm fine with merging this as is for now, but perhaps the nginx config won't end up under `systemd/`.

**Comment by harleypig** [comment]
Done. And don't expect the nginx file to stay there, or even unchanged. :) I didn't take the time to create a real template, just deleted my identifying info from it.

**Comment by harleypig** [comment]
fix above comment: And I don't expect the nginx file to stay ...

**Comment by simonmichael** [comment]
Good enough, thanks for the contribution!

**Pull request merged**
