### PR TITLE
lib: Replace some utility functions with library functions.

### PR DESCRIPTION
**Pull request by Xitian9**
Minor clean-up.

### CODE REVIEW

**Comment by simonmichael** [comment]
Thanks @Xitian9, I'll review soon. That CI failure is my fault.

**Comment by Xitian9** [comment]
Actually, looking at the definition of `Journal`, I think this is not actually correct. It looks like `mempty` is only a left unit for `mappend`, not a right unit, i.e. `mappend` is right-biased in some fields.

I'll remove the relevant parts from this pull request, but this seems like something which should be changed in general. I can think of two options:
(1) Journal is just a Semigroup, not a Monoid (possibly a member of Semigroup and Default).
(2) We change the definition of `mappend` to prefer non-empty fields.

(1) Seems like the most straightforward solution. What do you think?

**Comment by simonmichael** [comment]
@Xitian9, thanks for the cleanups. We currently support GHC 8.0 and up, and should build warning-free; for this it looks like more work is needed. You can use the "buildtest" make rules to check this, eg:
```
make help-buildtest
make buildtest-all
make buildtest-stack-8.0.yaml
```

**Comment by Xitian9** [comment]
It should now build without error on stack 8.0 and above. I'm not sure why CI isn't running.

**Comment by simonmichael** [comment]
Looking good. Thank you!

**Pull request merged**
