### PR TITLE
Various fixes for combining transaction filtering with valuation.

### PR DESCRIPTION
**Pull request by Xitian9**
Addresses #1625, #1629, and #1630.

### CODE REVIEW

**Comment by simonmichael** [comment]
> note that aregister currently only tests queries other than
# "cur:" and the account query when given the --txn-dates option. Who knows why

I didn't recover the full detail (and have some small cleanups to push), but I bet it's something to do with "those are the only kinds of query that don't disturb the historical running balance".

**Comment by simonmichael** [comment]
Looks good to me!

**Comment by simonmichael** [comment]
@Xitian9, I'd like to cherry-pick these from master to 1.22-branch:

- 2da0e6714 * fix: Add balancing amounts in periodic transactions before applying auto-postings. (#1412)
- 9df574b3c * fix: reg: register --related should not create duplicate postings when more than one posting in a transaction matches. (#1629)
- 6528f2559 * fix: lib: Filter postings before performing valuation and costing in MultiBalanceReport, PostingsReport, EntriesReport, and AccountTransactionsReport. (#1625, #1630)

There are conflicts with 6528f2559 at least, I think it depends on some big refactors which I'd rather not take for 1.22-branch. Could you give it a try, and see if you can get these cherry-picked with reasonable confidence ?

**Comment by Xitian9** [comment]
I'll give it a shot.

**Comment by Xitian9** [comment]
I can cherry-pick 2da0e67 and 9df574b pretty easily, but give that 6528f25 still has problems that need to be sorted out with the aregister report, I would hold off on that one until I've sorted those out, if you don't mind.

**Comment by Xitian9** [comment]
Or I can just cherry-pick the changes to non-aregister reports for now, and we can merge the aregister report changes when those are done.

**Comment by Xitian9** [comment]
Well, I managed to cherry-pick all of them (#1635). But we'll still have the problems with aregister, which I presume we'll move over when they're done.

**Comment by simonmichael** [comment]
Thanks! I thought 1.22-branch was free of the aregister breakage. I guess it got pulled in somehow ?

**Comment by Xitian9** [comment]
Indeed, 1.22-branch seems to pass all the new aregister tests. I guess it's fine.

**Comment by simonmichael** [comment]
1.22 branch gets the aregister problem when I merge your last commit:

- 2059d86ab * fix: lib: Filter postings before performing valuation and costing in MultiBalanceReport, PostingsReport, EntriesReport, and AccountTransactionsReport. (#1625, #1630)

**Comment by Xitian9** [comment]
Aha, then the problem is with the fix itself.

Do you think merging #1636 into 1.22-branch is best, or would you rather a more minimal fix?

**Comment by simonmichael** [comment]
Ideally, minimal code changes in 1.22-branch, reducing its scope and risk of additional issues. It's fine if 1.22.1's aregister still has some problems, as long as it's not worse that 1.21. 

Are we in a situation where it's not really feasible to fix just the 1.22 regressions in 1.22.1, without pulling in the extensive refactors/renames/etc. I was trying to avoid ? I can imagine we might have to pull them all in, in that case.

**Comment by Xitian9** [comment]
I think it should be possible to merge #1636 without bringing any other refactors. However, #1636 itself is a big refactor of `accountTransactionsReport`.

If we're looking to avoid those, I would drop the aregister changes from #1635. We would still be left with cur: and amt: matching after valuation rather than before, but we wouldn't have the historical postings problem.

**Comment by simonmichael** [comment]
Well.. matching after valuation is one of the changes we want to undo in 1.22.1, so we need that.

**Comment by simonmichael** [comment]
(If the commits are just too interdependent, let me know and I'll have a look at merging "everything" into 1.22-branch.)

**Comment by Xitian9** [comment]
I think just merge #1636 in and that will fix it. Nothing else should be required.

**Comment by simonmichael** [comment]
> I think just merge #1636 <https://github.com/simonmichael/hledger/pull/1636> in and that will fix it.
> 
Easier said than done.. cherry picking has lots of conflicts. Literally merging merges everything from master - 112 commits and some conflicts.

**Comment by Xitian9** [comment]
Really? That surprises me. Let me give it a shot.

**Comment by Xitian9** [comment]
I've now cherry-picked the commits from #1636 and included them in #1635.

**Pull request merged**
