### PR TITLE
Allow selecting the date range from the chart

### PR DESCRIPTION
**Pull request by raboof**
By dragging a region with the mouse

select

### CODE REVIEW

**Comment by simonmichael** [comment]
Great!

When zoomed in, it doesn't seem to always pick the dates you'd want. Eg to view the transactions on a single day, you'd expect that selecting a region that contains the dot will show the transactions on that day, but sometimes that day is excluded. See if you can reproduce, and maybe expand the selection in a smart way ?

**Comment by raboof** [comment]
> to view the transactions on a single day, you'd expect that selecting a region that contains the dot will show the transactions on that day, but sometimes that day is excluded. See if you can reproduce, and maybe expand the selection in a smart way ?

Aah, indeed it was rounding down for the 'to' date, where it should been rounding up. Updated.

**Comment by simonmichael** [comment]
That's much better. One more thing that may not be your fault, but would improve the feature I think. Testing with `make ghci-web`, `:main -f examples/sample.journal`:

- Click assets, select the two months enclosing the three central points.
  In the query field I see the span I selected, eg `date:2008/4/30-2008/6/29`.
  But the chart is shrunk to the points' span (6/1 to 6/3).
  It would be more intuitive if it showed the span that was selected.

**Comment by raboof** [comment]
> One more thing that may not be your fault, but would improve the feature I think

I agree, but indeed pretty sure that's not directly related to this PR. Maybe let's create a separate issue for that?

**Comment by simonmichael** [comment]
Ok, would you mind creating it ? Merging this one, thanks a lot !

**Comment by raboof** [comment]
> Ok, would you mind creating it ?

Sure, #1485

> Merging this one, thanks a lot !

Thanks for the merge!

**Pull request merged**
