### PR TITLE
Hakyll std

### PR DESCRIPTION
**Pull request by ehildenb**
Addressing #744.

Unfortunately the long pandoc build times are still present, I couldn't get it to work without adding `--package pandoc` to the invocation of `ghc` which builds `tools/pandoc-site.hs`. They only happen on `./Shake website-render` though.

Dependencies on Hakyll and Blaze completely removed. Instead a pandoc filter and the Shake file are used to build the website.

I have tested locally, and everything under `site/_site` builds exactly the same except for:

1.   Links now have the `title="LINK_NAME"` attribute added, because of how pandoc renders links (due to b5c320c).
2.   The table of contents ordered lists now have the attribute `type="1"` added (and HTML layout is slightly different), because pandoc renders ordered lists with the type added by default (due to fb42d6a).
3.   The spacing on table of contents is different (due to 770b58b).
4.   Useless file `coins.svg` is also copied into each website `images/` directory as well, can't avoid this without listing out many more files in `./Shake.hs` (due to 1254557).
5.   Large parts of the HTML are indented due, and many apostrophes are replaced with `&#39;` because of how pandoc renders documents (due to 3514b78).

I think this is ready for merge, future action needed is to replace `tools/pandoc-site.hs` with a Lua script version. This will remove the long pandoc build times. Alternatively, figure out how to make either `hpack` or `stack` build `tools/pandoc-site.hs` correctly so it caches dependencies for us (including the pandoc dependencies). I fought with it a bit, but just don't understand enough about how these things work.

### CODE REVIEW

**Comment by simonmichael** [comment]
Very nice! I will look asap.

**Comment by simonmichael** [comment]
Looks great ehildenb. I'll just paste some notes here.

Can you add a module doc to pandoc-site.hs summarising what it does.

Is the "from https://github.com/blaenk/blaenk.github.io" comment still accurate ?

Perhaps we can avoid adding site-building deps to stack-ghc8.2.yaml, which forces a slow pandoc build on folks trying to build hledger with it.

Does the double slash in "site/_site//*.html" in Shake.hs mean something ? Or is it just a workaround for dropDirectory2 ?

In the Makefile, the site-* rules need cleanup. I'll do this.

Docs we'll need to update: probably the developer workflows and contributor guide on the wiki.

**Comment by simonmichael** [comment]
It seems to build everything cleanly in about a minute on my system and I expect is already more robust than what we had. Merging, let's refine in master. Thank you!

**Comment by ehildenb** [comment]
The double slack `//` in Shake means "match any number of path components, including zero". So `site/_site//*.html` will match `site/_site/index.html`, and will also match `site/_site/doc/1.2/csv.html`. It's so that the same rule can be used to build all the html files using pandoc.

**Pull request merged**
