### PR TITLE
print: differentiate line indent (4spc) from pre-comment space (2spc)

### LINKED ISSUE #1047: Number of spaces used before comment separator in print should be configurable
By default `ledger` outputs comments with 2 spaces before the separator `;`

```ledger
2019/06/11 (TXNID) Office Building Complex
    Expenses:Building:Dues                 ₺1.020,00  ; date: 2019/04/01
    Expenses:Building:Dues                 ₺1.020,00  ; date: 2019/05/01
    Expenses:Building:Dues                 ₺1.020,00  ; date: 2019/06/01
    Expenses:Fees:Banking                      ₺6,75  ; payee: Bank Name
    Assets:Bankaccount                    ₺-3.066,75
```
On the other hand `hledger` uses four:
```ledger
2019/06/11 (TXNID) Office Building Complex
    Expenses:Building:Dues                 ₺1.020,00    ; date: 2019/04/01
    Expenses:Building:Dues                 ₺1.020,00    ; date: 2019/05/01
    Expenses:Building:Dues                 ₺1.020,00    ; date: 2019/06/01
    Expenses:Fees:Banking                      ₺6,75    ; payee: Bank Name
    Assets:Bankaccount                    ₺-3.066,75
```

I find the four spaces somewhat excessive (and in more verbose examples such as with tags the extra space can cause unnecessary wrapping or scrolling) and would like to configure it to output 2 instead. I don't see any option to configure this preference.

Note `ledger` requires at least one space to parse comments, `hledger` doesn't need any at all, so this isn't a parsing issue, it is just a preferred output format issue.

### PR DESCRIPTION
**Pull request by alerque**
Fixes #1047.

- [x] Split `indent` value so comment separation spaces can be different from posting indents
- [x] Update examples in documentation
- [x] Update output of tests

Optionally...

- [ ] Make number of spaces user configurable

### CODE REVIEW

**Comment by alerque** [comment]
I might be stuck on this one. I got part of the way there in that line level comments properly indent with 4spcs and inline comments are preceded by 2spcs, but the test cases include a multi line comment that gets split on newlines, and I don't know how to handle that. Right now I'm flunking the tests suite because its inserting 2spcs for the wrapped comment newlines instead of the expected 4.

https://github.com/simonmichael/hledger/blob/master/hledger-lib/Hledger/Data/Transaction.hs#L571

**Comment by simonmichael** [comment]
Thanks! I'll take a look later if you don't beat me to it.

**Comment by alerque** [comment]
The branch is open to your pushes ;-)

Interestingly the test case that's failing cannot be replicated from normal input, it is only even possible from Haskell programmatically generating the transaction object.

**Comment by alerque** [comment]
I was looking into making this an option, I'm not sure where the option should go. It would go the same place as the new flag(s) for #1045 go, but I can't figure out where that would go to affect `print`, `print-unique`, and any other places affected.

On even further review, I'm not convinced making this configurable is even such a great idea. Two spaces seems to be pretty universal already, and allowing less breaks some things (`ledger` for example would parse that okay in postings, but not in the transaction description line).

I guess the question is: is there actually any demand for MORE than 2 spaces?

**Comment by simonmichael** [comment]
Making what an option.. the number of spaces before a same-line comment ? I don't think we need to. I suppose the few folks who commit and compare report output to detect changes, will notice diffs and maybe ask why we are bothering them with this. Hopefully not.

**Comment by alerque** [comment]
In that case I think this is ready to go.

**Comment by simonmichael** [comment]
Thanks!

**Pull request merged**
