### PR TITLE
cli: added --transpose to "balance" command

### PR DESCRIPTION
**Pull request by adept**
This implements balance --transpose for text and csv outputs, potentially closing #955 

People braver than me could implement it for HTML as well :)

### CODE REVIEW

**Comment by simonmichael** [comment]
Thanks!

**Comment by simonmichael** [comment]
Still to do, if anyone has the urge: 

- balance command's HTML output
- balancesheet, incomestatement, cashflow

**Comment by adept** [comment]
note: balancesheet, incomestatement, cashflow are all implemented via compoundbalancecommand, however transposing its final table in a naive way does not work as it has rather complex internal structure.

**Comment by erikryb** [comment]
Great! I have updated issue #955 to show the progress.

**Pull request merged**
