### PR TITLE
GHC 8.0 compatibility

### PR DESCRIPTION
**Pull request by ony**
Get it built on GHC 8.0.2

### CODE REVIEW

**Comment by simonmichael** [comment]
Wow, how quickly compatibility breaks if you're not testing it. Thanks for this.

**Comment by krlmlr** [comment]
I'm new to Haskell. I can't install on Ubuntu with `ghc` 8.0.2, seeing:

```
$ cabal install hledger-lib-1.9.1
...
[32 of 48] Compiling Hledger.Read.Common ( Hledger/Read/Common.hs, dist/build/Hledger/Read/Common.o )

Hledger/Read/Common.hs:933:33: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.Compat.<>’,
                             imported from ‘Prelude.Compat’ at Hledger/Read/Common.hs:23:1-39
                             (and originally defined in ‘Data.Semigroup’)
                          or ‘Data.Monoid.<>’,
                             imported from ‘Data.Monoid’ at Hledger/Read/Common.hs:38:1-18
cabal: Leaving directory '/tmp/cabal-tmp-17930/hledger-lib-1.9.1'
cabal: Error: some packages failed to install:
hledger-lib-1.9.1 failed during the building phase. The exception was:
ExitFailure 1
```

Does this PR solve that problem? When will I be able to use `cabal install` to install it, or how do I install from GitHub? I tried `cabal install cabalg` but that didn't give me a `cabalg` binary on the path.

**Comment by simonmichael** [comment]
Thanks for the report. Yes, I think so. I will make a bugfix release soon. Meanwhile you can try the instructions for installing from github, on the download page. There is no such thing as cabalg.

**Comment by krlmlr** [comment]
I'm seeing the same error when running `./cabal-install.sh` from a clone of the project (`ghc` 8.0.2, Ubuntu 17.10). Would you like me to file a new issue?

The following works for me (from #709):

```sh
stack --system-ghc --no-install-ghc --stack-yaml stack8.0.yaml install
```

**Comment by simonmichael** [comment]
@krlmlr yes please, let's open a reminder issue.

**Pull request merged**
