### PR TITLE
hledger-web: add links to accounts in register transactions

### PR DESCRIPTION
**Pull request by thielema**
In hledger-web: `http://localhost:5000/register?q=inacct%3A%22MyAccount%22` the accounts in the transactions were not linked like they are in the `/journal` mode. I have added them.
I had to copy some code from `AccountTransactionsReport` and I do not use the `acct` result of `accountTransactionsReport` anymore. So maybe, one should adapt `hledger-lib`, also?

### CODE REVIEW

**Comment by simonmichael** [comment]
@thielema thanks!

Pro: 
In register items you can immediately click on the To/From Accounts to go to that account's register, instead of clicking the date to go via the journal view.
All to/from accounts are shown, not just the ~2 that fit without line wrapping.

Con:
Complex transactions take more vertical space, due to line wrapping in Description and To/From Accounts. Descriptions are harder to read. Visual similarity to a physical checkbook register is weaker.

I'm not a heavy user of hledger-web, but personally I value the consistent visual row height and readable descriptions slightly more than these new links. I worked pretty hard to prevent this kind of line wrapping. Could some other hledger-web users try this and give their opinion.

**Comment by thielema** [comment]
On Sun, 9 Jun 2019, Simon Michael wrote:

> Con:
> Complex transactions take more vertical space, due to line wrapping in Description and To/From Accounts.
> Descriptions are harder to read. Visual similarity to a physical checkbook register is weaker.

I may enable the links via a command-line option of hledger-web.

**Comment by simonmichael** [comment]
Other ideas: 
- just hyperlink the existing layout (treat layout changes as a separate issue)
- a javascript button to reveal full line-wrapped content
- show full content on mouseover
- truncate long content in a smarter way so that you can see all of it by shrinking your font or enlarging your window

**Comment by thielema** [comment]
On Mon, 10 Jun 2019, Simon Michael wrote:

> Other ideas:
>
>  *  just hyperlink the existing layout (treat layout changes as a separate issue)

Ok, I have tried to preserve the former layout. It makes the code more 
complicated but it works.

Unfortunately, it seems I got the Git merging wrong. I wanted to 'pull 
--rebase' in order to update my commits while preserving yours. It seems 
Git did it the other way round. :-( Maybe it is easier for you to cherry 
pick my three commits?

**Comment by simonmichael** [comment]
@thielema looks great! Thank you, I have rebased and merged.

**Comment by simonmichael** [comment]
Which I thought would mark this pull request accepted - maybe it will if you force-pull from master to your thielema:register-account-links branch. Otherwise I'll just close it.

**Pull request closed without merging**
