### PR TITLE
doc: clarify virtual prices

### PR DESCRIPTION
**Pull request by tbm**

### CODE REVIEW

**Comment by simonmichael** [comment]
What's going on here ? Adding a hyperlink to "Like" ?

**Comment by tbm** [comment]
I'm just removing an empty bullet point in the list.  See 4 in the pic

hledger

Hmm, now that I look at it again, I think it's intentional.  4 being (@) and 5 being (@@).  I'll propose an alternative patch tomorrow to make it clearer.

**Comment by tbm** [comment]
Huh, and I have no idea where that link on Like came from...

**Comment by tbm** [comment]
Is this patch better?

**Comment by simonmichael** [comment]
Thank you very much!

**Pull request merged**
