### PR TITLE
add --uncleared option for Ledger compatibility ?

### PR DESCRIPTION
**Pull request by hackeryarn**
@simonmichael is this what you had in mind as the fix for #367?

I am not sure if you want this option documented on the website since it's primarily there to support `ledger-mode`, but I will be happy to add it.

### CODE REVIEW

**Comment by simonmichael** [comment]
Thanks! Yes, that's what I was talking about. Do you think it's a worthwhile addition, or not worth the cruft ? If the former, yes we should probably make sure it's documented. Maybe I'd mention that it's for compatibility, something like "equivalent to --unmarked --pending, for Ledger compatibility".

**Comment by hackeryarn** [comment]
I personally don't think it's worth the cruft. There is already a good explanation of how to combine `-UP` to get the same results. Adding two ways to do the same thing may confuse people more than it will help.

I do like the idea of adding the compatibility note to the cli options and text file. 

I would also like to add unit tests for this feature under `rawOptsToReportOpts`. But I am not sure how format the test if the output of the function under test is wrapped in `IO` (e.g. `IO ReportOpts`). Sorry, I am a bit new to Haskell and never used `easytest` before.

**Comment by simonmichael** [comment]
That sounds great. A test would be fine but doesn't seem essential ? I'm not sure what there is there that's likely to break.

**Comment by hackeryarn** [comment]
@simonmichael I updated the text to include a note about compatibility. Please let me know if there is anything else you see missing.

**Comment by simonmichael** [comment]
@hackeryarn sorry if I was unclear. Considering what you said, I agree with you ("I personally don't think it's worth the cruft").

**Comment by simonmichael** [comment]
So I guess we'll close this ? Can reopen if someone finds it worthwhile in future.

**Comment by hackeryarn** [comment]
Sorry, why are we closing this? The of this was to bring the API in line with the ledger API so the Emacs ledger-mode could run all operations. At least I would very much love to see this merged.

**Comment by simonmichael** [comment]
Ok I misunderstood, I thought we both felt this was not worth the added UI cruft and confusion. So you feel adding the `--uncleared` option is worthwhile to work more smoothly with ledger-mode ? Could we improve ledger-mode instead ?

**Comment by hackeryarn** [comment]
That's a good idea! I just checked, and it's only used in one place inside `ledger` mode. I will try to go that route since the same effect can be achieved by combining two flags in `hledger` and `ledger`. 

Let's close this issue for now unless `ledger-mode` pushes back on the PR.

**Comment by simonmichael** [comment]
Great. Feel free to link it here.

**Pull request closed without merging**
