### PR TITLE
WIP: Replace Parsec with Megaparsec

### PR DESCRIPTION
**Pull request by rasendubi**
This still a work in progress and doesn't compile. The main reason is csv package ParseError from Parsec which is a distinct type from ParseError from Megaparsec.

### CODE REVIEW

**Comment by simonmichael** [comment]
@rasendubi, thanks for this - I'll be looking at it after next release.

Today's megaparsec release makes it compatible with GHC 7.6, which is good. Adopting it would mean hledger no longer builds with GHC 7.4, which is a pity but probably acceptable now.

**Comment by davelab6** [comment]
Can this be closed?

**Comment by simonmichael** [comment]
I'd like to get it completed and merged. If no one else does, I'll work on it as soon as open bugs are cleared.

**Comment by cocreature** [comment]
FYI I’ve picked this up and hope to have it finished by the end of next week.

**Comment by simonmichael** [comment]
Continued at #366, closing this one.

**Pull request closed without merging**
