### PR TITLE
New periodic expressions for every weekday et al

### PR DESCRIPTION
**Pull request by la-wu**
Possible implementation for https://github.com/simonmichael/hledger/issues/1517

### CODE REVIEW

**Comment by simonmichael** [comment]
Nice! Quick thoughts:

- I'd prefer `every weekendday` to `every weekend` - though it looks weird I think it would be clearer, `every weekend` sounds like one event per week.
- Are both singular and plural forms accepted ? I see `weekdays` in the doc.
- Would it not be better to keep DayOfWeek in case we ever want to represent a single day, and work with [DayOfWeek] ?
- The `every <multiple disjoint selectors>`, like `every mon|thu` is interesting. I think that's new behaviour. Period expressions continue to grow a bit out of control - it might be ok to add it as a special case for now, but is it something we should think about supporting more generally ? `every Q1|Q3`, `every feb|aug`, etc.

**Comment by la-wu** [comment]
> * I'd prefer `every weekendday` to `every weekend` - though it looks weird I think it would be clearer, `every weekend` sounds like one event per week.

Sure, I'll change that. Probably good to make it seem weird and obvious rather than use `weekend` with potential ambiguity.

> * Are both singular and plural forms accepted ? I see `weekdays` in the doc.

Yes it supports the 'compact' forms `~ weekdays` and `~ weekenddays` along with the `every <singular>`

> * Would it not be better to keep `DayOfWeek` in case we ever want to represent a single day, and work with `[DayOfWeek]` ?

I intended to represent a single day by having `DaysOfWeek` contain exactly 1 element. Since  `DaysOfWeek` should never be empty, potentially a non-empty list would be clearer?

> * The `every <multiple|disjoint|selectors>` (`every mon|wed|fri`) is interesting. I think that's a new capability ? Period expressions continue to grow a bit out of control - it might be ok to add it as a special case for now, but is it something we should think about supporting more generally ? `every Q1|Q3`, `every feb|aug`, `2020|2022|2024` (<- no `every`), etc. ?

Yes I thought it was a relatively straightforward parser to create and solves the issue mentioned in https://github.com/simonmichael/hledger/issues/1517#issuecomment-848592937 where we might have different spans represent the 'weekdays' vs 'weekenddays'. I think limiting the usage would be a reasonable start. Unless there are other compelling examples where it could be useful.

> * [Or contrarily, is it time to think about supporting more standard ISO recurring syntax ?]

I think that could be done independently of this particular feature. Is there a common use case for said syntax?

**Comment by simonmichael** [comment]
> The periods will be built between specified days.

This wording confused me, "between" sounds like the span between the days would be included. I'll adjust it a little while resolving the conflict.

**Comment by simonmichael** [comment]
https://hledger.org/hledger.html#period-expressions changed today, and I am reconciling this with it. Here's the WIP doc:

> Weekly on custom day(s):
> 
> - `every Nth day of week` (`th`, `nd`, `rd`, or `st` are all accepted after the number)
> - `every WEEKDAYNAMES[|WEEKDAYNAME|...]` (one or more full or three-letter english weekday names, case insensitive)
> - `every weekday` (same as `every mon|tue|wed|thu|fri`)
> - `every weekendday` (same as `every sat|sun`)
> 
> (The last three above are the only form that generate multiple dates per interval.)

Are the alternate `~ weekdays` and `~ weekenddays` forms worth it ? I'm inclined to omit them to keep things feeling a bit more consistent.

Note the final sentence. All other forms specify one date within each interval/subperiod. I feel there might be a bit of ambiguity here, which this doc also touches on:

>  `-p "every 2nd day of week"` | periods will go from Tue to Tue

Ie, most of the time we are interested in the intervals bounded by these dates, so eg `register -p 'every tue'` groups the postings in each tuesday..tuesday period. So what does `register -p 'every tue|wed|fri'` do ? I think it still reports all the postings in the week, but with the week further divided into three periods (tuesday, wednesday-thursday, and friday-monday). I guess that's ok.

I found myself wanting to write -p 'every tue,wed,fri' instead. This might be clearer and more shell friendly ?

**Comment by simonmichael** [comment]
Just  to complete that thought: we interpret period expressions in two different ways:

1. With `-p`, the generated dates delimit report subperiods.
2. In `~` periodic transaction rules, with `--forecast` or `balance --budget`, each date generates a transaction.

**Comment by simonmichael** [comment]
> So what does register -p 'every tue|wed|fri' do ?

Similarly, `register -p 'every weekday'` creates five periods per week: mon, tue, wed, thu, fri-sun:
```
~ every day
    (a)  1
```
```
$ hledger reg --forecast date:thismonth
2021-08-17                                 (a)                                        1             1
2021-08-18                                 (a)                                        1             2
2021-08-19                                 (a)                                        1             3
2021-08-20                                 (a)                                        1             4
2021-08-21                                 (a)                                        1             5
2021-08-22                                 (a)                                        1             6
2021-08-23                                 (a)                                        1             7
2021-08-24                                 (a)                                        1             8
2021-08-25                                 (a)                                        1             9
2021-08-26                                 (a)                                        1            10
2021-08-27                                 (a)                                        1            11
2021-08-28                                 (a)                                        1            12
2021-08-29                                 (a)                                        1            13
2021-08-30                                 (a)                                        1            14
2021-08-31                                 (a)                                        1            15
$ hledger reg --forecast date:thismonth -p 'every weekday'
2021-08-17              a                                                             1             1
2021-08-18              a                                                             1             2
2021-08-19              a                                                             1             3
2021-08-20..2021-08..   a                                                             3             6
2021-08-23              a                                                             1             7
2021-08-24              a                                                             1             8
2021-08-25              a                                                             1             9
2021-08-26              a                                                             1            10
2021-08-27..2021-08..   a                                                             3            13
2021-08-30              a                                                             1            14
2021-08-31              a                                                             1            15
```
(Using a periodic rule and --forecast here just to generate some transactions, then -p to group these into subperiods.)

**Comment by simonmichael** [comment]
So is the above ok ? Alternative behaviour would be for `register -p 'every weekday'` to show five one-day-periods per week: mon, tue, wed, thu, fri, with sat-sun excluded from the report. This would be new behaviour: non-adjacent report periods, which might cause problems somewhere else; more testing would be needed.

This is a small niche feature at this stage, but we like to sweat the details (so users don't have to). Which `register -p` behaviour seems more intuitive here ?

**Comment by lubieowoce** [comment]
> Alternative behaviour would be for `register -p 'every weekday'` to show five one-day-periods per week: mon, tue, wed, thu, fri, with sat-sun excluded from the report.

this is what i'd expect. the first behavior - gluing fri-sat-sun together into one period (AFAIU) - seems pretty counterintuitive to me – wouldn't that cause the report to include transactions that happened on sat/sun?

**Comment by simonmichael** [comment]
Yes it does. I agree it's counterintuitive, at first. It is consistent though. 

If on the contrary `reg -p "every weekday"` generates five single-day periods per week and excludes sat/sun, then we'd expect `reg -p "every mon|tue"` to generate two single-day periods per week, and `reg -p every tue` to generate one single-day period per week... ? No, traditionally this last one generates a seven-day period per week. 

You could say there's a new rule: when multiple days are specified (|, weekday, weekendday), disjoint periods will be generated, one for each day. Is that intuitive and useful enough to be worthwhile ? Will it generalise to other, larger kinds of disjoint period we may add later ? Do we have enough practical uses that it's worth spending time on this now ?

Or, we can postpone that and just document the current behaviour, on the basis that it is intended for forecasting/budgeting and defining strange sub-week report periods isn't needed.

**Comment by lubieowoce** [comment]
made some ascii diagrams to verify my understanding.
a `===>` symbolizes a period (right-exclusive) on a timeline. the periods above the number line are according to option 1, the periods below it are option 2.

```
every weekday = every mon|tue|wed|thu|fri

|==>|==>|==>|==>|==========>
1---2---3---4---5---6---7---
|==>|==>|==>|==>|==>

every tue|thu

===>|======>|===============
1---2---3---4---5---6---7---
    |==>    |==>

1. (above line) every x, start a new period

2. (below line) every x, start a new period lasting y
      in this case, y = 1 day.
      possible default: y = time resolution used in rule.
       every <day>   => y = 1d
       every <month> => y = 1mo
```

**Comment by simonmichael** [comment]
That's correct. Currently, -p always generates adjacent report periods with no gaps between. Proposed option 2 would sometimes generates disjoint periods with gaps.

**Comment by la-wu** [comment]
The implemented behavior was chosen since the report intervals are really defined by the start dates of each interval. Thus the period expressions where multiple days are specified can be thought of as starting a new sub-period every specified day. With that in mind, I don't think this interval behavior is any less intuitive than that `every monday` generates intervals that contain non-mondays (it generates week-long intervals beginning every monday). Perhaps we could indicate that the report intervals are specified as `beginning on every ...` with the syntax or documentation.

I do think it's awkward that intervals are no longer always directly comparable since they span a different number of days and I'm not sure how useful the reports will be when aggregated as such. I've never needed such granular breakdowns so I don't have a good use case for either aggregation behavior.

**Comment by simonmichael** [comment]
I'd like get this merged without our spending much more time on it. @la-wu, I heard no objection so could you

- drop the `weekdays`/`weekenddays` alternative spellings
- use `,` instead of `|`

and we'll leave it working as it is now - generating adjacent but possibly uneven periods - for now, avoiding additional work and risk.

**Comment by simonmichael** [comment]
@la-wu I meant to get rid of just `weekdays` and `weekenddays`, but to keep `every weekday` and `everyweekendday` - those are the original goal after all. Sorry for the confusion.

**Comment by simonmichael** [comment]
Your doc was good but I couldn't resist trying to clarify things a bit more - sorry
(cf https://hledger.org/dev/hledger.html#periods-or-dates-). 
This is now merged, thank you!
(Also, --forecast=PERIOD now rejects a report interval, since I got confused wondering why `--forecast='every weekendday from today to next month'` didn't work.)

**Pull request merged**
