### PR TITLE
WIP: change date formatting to yyyy-mm-dd

### PR DESCRIPTION
**Pull request by bwignall**
Relates to https://github.com/simonmichael/hledger/issues/933 .

For now, this is submitted as multiple commits, each commit being a standalone task. The change to the formatting itself happens in 99a6e70 ; the remainder of the files changed are to get tests working again (no tests themselves should have changed, only the "expected" output).

`make functest` has five failures with the present code; example below.

Docs have not yet been updated to reflect new format.

### CODE REVIEW

**Comment by bwignall** [comment]
Example of failing test:

> :tests/journal/posting-dates.test:1: [Failed]
> Command:
> /home/me/hledger/.stack-work/install/x86_64-linux-tinfo6/longcodehere/8.8.1/bin/hledger  -f- register
> Expected stdout: 
> /^2000/03/04/
> Got stdout:      
> 2000-03-04                      a                                0             0
> 
>

**Comment by simonmichael** [comment]
@bwignall I rebased and fixed the remaining tests, at https://github.com/simonmichael/hledger/tree/date_formatting . I'm going to use this for a bit and look for issues. Looking good!

**Comment by maralorn** [comment]
Thx! Really nice! Please write it big in the Changelog. I think I have workflows that rely on the output of print being stable.^^

**Comment by bwignall** [comment]
@simonmichael , thanks for doing that.

A non-update: I am trying to check/update the docs (following https://hledger.org/CONTRIBUTING.html#work-on-docs ), but I am struggling with figuring out Shake (all invocations give `Shake: site: getDirectoryContents:openDirStream: does not exist (No such file or directory)`). I presume something in my environment is in a bad state...

**Comment by simonmichael** [comment]
Sorry about that @bwignall. I think you need to clone (or symlink) the hledger_site repo as `hledger/site`. I think doc/README and CONTRIBUTING.md need an update.

**Comment by simonmichael** [comment]
PS since this is quite conflictful I'm happy to merge this and update the docs afterward. Chat me if I can help. https://hledger.org/#help-feedback

**Comment by bwignall** [comment]
@simonmichael , as you prefer. I am happy to make the docs a separate PR, if that makes things easier for you.

Running `git clone https://github.com/simonmichael/hledger_site.git site` and `stack install pandoc` (1.x was in the installation location, but 2.x was needed) seemed to get my environment into a better place.

**Comment by simonmichael** [comment]
If you don't mind handling the conflicts, then keep going here (What more is needed ?) Just let me know when to merge.

**Comment by bwignall** [comment]
@simonmichael , here are the things I have in my notes (not guaranteed exhaustive) on outstanding questions:

* Why does tests/rewrite.test sometimes output yyyy/mm/dd? Example: test 7, https://github.com/bwignall/hledger/blob/date_formatting/tests/rewrite.test#L239

* Same question for tests/register/depth.test. Example: test 3, https://github.com/bwignall/hledger/blob/date_formatting/tests/register/depth.test#L46

* Same question for tests/pivot.test. Example: end, https://github.com/bwignall/hledger/blob/date_formatting/tests/pivot.test#L135

* Same question for tests/cashflow.test. Example: test 1, https://github.com/bwignall/hledger/blob/date_formatting/tests/cashflow.test#L10

* Same question for tests/incomestatement.test. Example: test 1, https://github.com/bwignall/hledger/blob/date_formatting/tests/incomestatement.test#L10

**Comment by bwignall** [comment]
I am digging into these now and will ask questions if I run into difficulties.

**Comment by bwignall** [comment]
@simonmichael , what do you think of merging now? There's one outstanding question on my checklist, but it seems minor. `git grep -i '%y/%m' | grep -v date-format` and `git grep -i '%04d/%02d' | grep -v date-format` do not show more places that need to be updated, except perhaps hledger-web/static/hledger.js , but I left that untouched.

While trying to update docs, I found that I could not build them on master (`git clone https://github.com/simonmichael/hledger.git hledger_master ; cd hledger_master/ ; git clone https://github.com/simonmichael/hledger_site.git site ; stack build ; make Shake ; ./Shake manuals`) or on my branch. Would you want to merge while that gets unblocked?

**Comment by simonmichael** [comment]
I'm ready if you are. Your doc building command looks right, what error do you see ?

**Comment by simonmichael** [comment]
PS: wow, 60 files changed! 👍🏻

**Comment by bwignall** [comment]
@simonmichael : merge away.

**Comment by bwignall** [comment]
And this is what I see when I run `./Shake manuals`:

```
./Shake manuals
"template" (line 5, column 12):
unexpected "/"
expecting "." or "$"
Shake: Error when running Shake build system:
  at want, called at src/Development/Shake/Internal/Args.hs:83:69 in shake-0.18.3-K6N2eLzVtai6jtZeWAmEIo:Development.Shake.Internal.Args
* Depends on: manuals
  at apply1, called at src/Development/Shake/Internal/Rules/Rerun.hs:41:5 in shake-0.18.3-K6N2eLzVtai6jtZeWAmEIo:Development.Shake.Internal.Rules.Rerun
* Depends on: hledger-lib/hledger_timedot.5
* Raised the exception:
user error (Development.Shake.cmd, system command failed
Command line: /bin/sh -c 'm4 -P -DMAN -I hledger-lib doc/common.m4 hledger-lib/defs.m4 hledger-lib/hledger_timedot.m4.md | pandoc --strip-comments -f markdown-smart-tex_math_dollars -s --template doc/manpage.nroff --lua-filter tools/pandoc-drop-html-blocks.lua --lua-filter tools/pandoc-drop-html-inlines.lua --lua-filter tools/pandoc-drop-links.lua -o hledger-lib/hledger_timedot.5'
Original command line: m4 -P -DMAN -I hledger-lib doc/common.m4 hledger-lib/defs.m4 hledger-lib/hledger_timedot.m4.md | pandoc --strip-comments -f markdown-smart-tex_math_dollars -s --template doc/manpage.nroff --lua-filter tools/pandoc-drop-html-blocks.lua --lua-filter tools/pandoc-drop-html-inlines.lua --lua-filter tools/pandoc-drop-links.lua -o hledger-lib/hledger_timedot.5
Exit code: 5
Stderr:
"template" (line 5, column 12):
unexpected "/"
expecting "." or "$"
)
```

**Comment by simonmichael** [comment]
@bwignall: rebased and merged (despite github not noticing). Thanks for the work!

That error seems to be from the /nowrap added to doc/manpage.nroff to keep pandoc 2.8/2.9 happy. Whatever pandoc you have now, I think you need a newer one. Sorry about that.

**Pull request closed without merging**
