### PR TITLE
lib: Sort accounts: positive first, negative second, higher magnitudes first within each.

### PR DESCRIPTION
**Pull request by Xitian9**
What do you think of this as a solution for #1283?

### CODE REVIEW

**Comment by Xitian9** [comment]
A tangential comment:
There seems to be a bit of overlap between the `normalbalance_` and `invert_` options. Perhaps they could be unified?
- `invert_` has the effect of multiplying all amounts in a PostingReport or BalanceReport by (-1), and no other effect (in particular, no effect on sorting. It can be toggled by a command flag.
- `normalbalance_` will affect the sorting order of BalanceReports, but it cannot be set by a command line toggle, only by being set in code. This is done in CompoundBalanceReport, where it also multiplies amounts by (-1).

**Comment by simonmichael** [comment]
Aren't those semantically different, and liable to get things muddled if combined ? 

normalbalance_ is a hard coded property of the account type (debit or credit), and comes from the laws of accounting. 

invert_ is a last-minute cosmetic sign flipper, intended for (a) getting the signs you want when using bal rather than is/bs and (b) general utility, purpose unknown.

**Comment by Xitian9** [comment]
Okay. I'm happy to drop this pull request. Another option is to make it so that `invert_` gets applied before sorting, which means it will affect sorting too. Let me know how you'd like to proceed.

**Comment by simonmichael** [comment]
Let's leave it.

**Pull request closed without merging**
