### PR TITLE
Replace --pretty-tables with --pretty, a general option.

### PR DESCRIPTION
**Pull request by Xitian9**

### CODE REVIEW

**Comment by Xitian9** [comment]
I feel like the author of the second commit should be `sed`, not me.

**Comment by simonmichael** [comment]
Needs an entry in the hledger manual I think, wherever color is mentioned. (Perhaps both should be mentioned at https://hledger.org/hledger.html#output as well ? Not urgent)

**Comment by Xitian9** [comment]
Docs added. Let me know what you think.

**Comment by fancsali** [comment]
I personally would prefer the ASCII to be default. There are so many different terminals around (think about stuff like Termux on Android), and ASCII is nice enough -- but something that falls apart by default is rather annoying.

**Comment by simonmichael** [comment]
@fancsali I'm sympathetic to this, but there's some value in having things be attractive by default. I'd like to quantify the risk so as to make the right trade-off here. Currently I don't have any real examples of where this would happen, can you think of one ?

**Comment by simonmichael** [comment]
Useful resources:
- https://en.wikipedia.org/wiki/Box-drawing_character

**Comment by simonmichael** [comment]
Here's one case from Serge in chat: Iosevka font configured in terminal and vs code, box drawing chars look ok in terminal but not when viewing the saved output in vs code

image

image

**Comment by Xitian9** [comment]
I've removed the change of default from this PR. The remaining changes should be inoffensive.

**Comment by simonmichael** [comment]
Thank you! 

We decided not to make pretty the default just yet. It's still something we'd quite like to do, but we need to search more for examples of breakage like the above. I'll keep this open for now.

**Pull request merged**
