### PR TITLE
Shell completion

### PR DESCRIPTION
**Pull request by schoettl**
Related to #945 

Comments?

Please don't merge yet, I want to enhance the completion behavior with `--files=`.

### CODE REVIEW

**Comment by schoettl** [comment]
Completion for Bash is finished, I think!

I can only provide completion for Bash. Scripts for other Shells (e.g. Fish, zsh) are welcome. I'll add a section in the README on how to use this "framework".

**Comment by simonmichael** [comment]
Nice @schoettl. I just added the (WIP) suffix to remind me not to merge, feel free to remove it now (I'd like to know if you have that access).

Would anyone like to do a little testing before I merge this ?

**Comment by schoettl** [comment]
Another bugfix for filename completion. I think, now it's functioning really good!

Some testers? ... before I remove the WIP in the title...

I'm not completely satisfied with it because I'm not sure if I fully understand Bash's completion system (`complete`, `compgen`, `compopt`).

**Comment by simonmichael** [comment]
Nice. Why version 1.1 ? You probably want to follow http://hledger.org/manual.html#queries

Let me know when you feel ready to have this merged.

**Comment by schoettl** [comment]
Oh, the search engine took me to the old doc. Fixed.

I also added `amt:<=`, `status:!`, and so on – these are not useful for completion but as documentation when the user presses tab twice to show possible completions. The disadvantage is that the number of suggestions is getting unwieldy. But it might be useful.

I'd like to wait a few more days before the merger. Maybe I come up with more ideas :)

**Comment by schoettl** [comment]
TODO for me: install current latest version (AUR, *-git?) of hledger and run make again to get latest option and command completions.

**Comment by schoettl** [comment]
Ready to merge.

**Comment by simonmichael** [comment]
This creates the shell-completions/ subdirectory, which contains a [README](https://github.com/simonmichael/hledger/blob/7644059d550a50fdc666c4a0e48bb2d445a848d9/shell-completion/README.md) for getting started. So far so good. How can we make this more discoverable and get folks likely to use it, using it ? Where could we mention it in the docs ?

**Comment by simonmichael** [comment]
Perhaps a new page in the Cookbook, & linked in the wiki sidebar ?

**Comment by simonmichael** [comment]
And/or.. a new section in the hledger manual ?

**Comment by schoettl** [comment]
I'd rather try to get package maintainers to install it together with hledger. Then, people who use auto completion will quickly find out. (Do we have a changelog?)

I'm not sure if it's worth a section in the `hledger` man page. I'm not aware of other programs that have a description of their shell completion in the man page.

A cookbook entry would be useful if the completion is not installed with the package manager. If it is installed automatically, I would just reference to the README to not duplicate content that is only relevant for developers. What do you think?

**Comment by simonmichael** [comment]
I think it's hard/slow to get new users; I would advertise everywhere that makes sense. And I would guess many/most hledger users aren't installing via system package. For myself trying this out, I'd like to follow some kind of link from the docs accessible from http://hledger.org .  But I'm going to merge the work so far, and we can follow up. Thanks for working on it!

**Pull request merged**
