### PR TITLE
lib: Make sure automatic postings generated from postings with more t…

### PR DESCRIPTION
**Pull request by Xitian9**
…han one commodity match on commodity symbol (#1582).

### CODE REVIEW

**Comment by Xitian9** [comment]
A related question. What should the output of this journal be?
```
= assets amt:>50
  (b)  *1

2017-12-14
  revenue:job   -10 USD
  revenue:job  -100 USD
  assets
```

Current output (both before and after this PR):
```
$ hledger -f- print --auto
2017-12-14  ; modified:
    revenue:job         -10 USD
    revenue:job        -100 USD
    assets
    (b)                 110 USD  ; generated-posting: = assets amt:>50
```

Possibly more correct output:
```
$ hledger -f- print --auto
2017-12-14  ; modified:
    revenue:job         -10 USD
    revenue:job        -100 USD
    assets
    (b)                 100 USD  ; generated-posting: = assets amt:>50
```

**Comment by Xitian9** [comment]
A better example of the question I was trying to ask above.
```
= assets amt:>50
  (b)  *1

2017-12-14
  revenue:job   -10 USD
  revenue:job  -100 EUR
  assets
```

Current output (both before and after this PR):
```
$ hledger -f- print --auto
2017-12-14  ; modified:
    revenue:job         -10 USD
    revenue:job        -100 EUR
    assets
    (b)                 100 EUR  ; generated-posting: = assets amt:>50
    (b)                  10 USD  ; generated-posting: = assets amt:>50

```

Possibly more correct output:
```
$ hledger -f- print --auto
2017-12-14  ; modified:
    revenue:job         -10 USD
    revenue:job        -100 EUR
    assets
    (b)                 100 EUR  ; generated-posting: = assets amt:>50
```

**Comment by simonmichael** [comment]
Thanks for the fix. I agree your proposed output looks more correct from a user perspective. (I guess internally, the auto posting rule is being applied before that posting is split into two single-commodity postings..)

**Comment by Xitian9** [comment]
Correct. I'll make that further change.

**Pull request merged**
