### PR TITLE
ui: support all results of showGenericSourcePos

### LINKED ISSUE #904: we should report the position of unbalanced transactions
Unbalanced transactions currently give an error like this:
```
hledger: could not balance this transaction (real postings are off by ...)
TXN...
```
- It should include the line number, in a standard format (like parse errors).
- Stretch goal: if this error shows up in hledger-ui --watch, pressing E should take you to the correct line.

### PR DESCRIPTION
**Pull request by ony**
Resolves #904

### CODE REVIEW

**Comment by simonmichael** [comment]
Nice. Is there a visible effect ? Could you add to the parser a "keep synced with ErrorScreen .hledgerparseerrorpositionp" note, and vice-versa ?

**Comment by ony** [comment]
> Nice. Is there a visible effect ? Could you add to the parser a "keep synced with ErrorScreen .hledgerparseerrorpositionp" note, and vice-versa ?
I've added comments.

As for visible effect - I'm not sure. I don't see much benefit in `ErrorScreen` that can appear only if error introduced after opening `hledger-ui` and with `--watch` usually refers to journal already openend in some editor.
This PR is for addressing:
>     * Stretch goal: if this error shows up in hledger-ui --watch, pressing E should take you to the correct line.
I.e. this one is merely to close that issue.

**Comment by simonmichael** [comment]
Ah I see. In userspeak: "ui: on unbalanced txn error, make E jump to right line". Thanks.

The error screen seems to me the best way to handle a journal file going bad while I'm hledger-ui --watch'ing it. Options? 0 jump to error screen (similar to hledger-web), 1 Exit the program, 2 ignore the changed journal and keep showing the old version, 2b also show a warning alert, 2c also clear the alert and reload when the file becomes valid again. 0 seems direct and useful.

**Comment by simonmichael** [comment]
Notes for possible fine tuning:

Current balance assertion error:
```
hledger: balance assertion error in "/Users/simon/src/PLAINTEXTACCOUNTING/hledger/examples/sample.journal" (line 27, column 28):
in transaction:
2008/06/02 save
    assets:bank:saving                $1 = $12345
    assets:bank:checking
after posting:
    assets:bank:saving    $1
balance assertion details:
date:       2008/06/02
account:    assets:bank:saving
commodity:  $
calculated: $1
asserted:   $12345 (difference: +$12344)
```

Current unbalanced transaction error:
```
hledger: "/Users/simon/src/PLAINTEXTACCOUNTING/hledger/examples/sample.journal" (lines 26-28)
could not balance this transaction (real postings are off by $-0.01)
2008/06/02 save
    assets:bank:saving             $1.00
    assets:bank:checking          $-1.01
```

Another possibility, includes "error" and brief description in the top line, better when grepping logs:
```
hledger: unbalanced transaction error in "/Users/simon/src/PLAINTEXTACCOUNTING/hledger/examples/sample.journal" (lines 26-28)
could not balance this transaction (real postings are off by $-0.01):
2008/06/02 save
    assets:bank:saving             $1.00
    assets:bank:checking          $-1.01
```

**Comment by simonmichael** [comment]
Or
```
hledger: unbalanced transaction error in "/Users/simon/src/PLAINTEXTACCOUNTING/hledger/examples/sample.journal" (lines 26-28)
Real postings should sum to $-0.01, should be zero:
2008/06/02 save
    assets:bank:saving             $1.00
    assets:bank:checking          $-1.01
```

**Pull request merged**
