### PR TITLE
Update brick to 0.19

### PR DESCRIPTION
**Pull request by felixonmars**

### CODE REVIEW

**Comment by simonmichael** [comment]
Thanks! I think we probably should support older brick for a while also, if necessary using CPP like [here](https://github.com/simonmichael/hledger/blob/master/hledger-lib/Hledger/Read/CsvReader.hs#L45).

**Comment by simonmichael** [comment]
cv https://github.com/fpco/stackage/issues/2617

**Comment by felixonmars** [comment]
Just updated. As a n00b in Haskell I am not very sure of my skills, let me know if I am not doing it correctly :P

**Comment by simonmichael** [comment]
Thanks! This was merged as ffe8b47.

**Pull request closed without merging**
