### PR TITLE
allow specifying valuation commodity, add -X

### PR DESCRIPTION
**Pull request by simonmichael**
Seems to work, more testing welcome. I'll merge this soon unless anyone has suggestions.

This is for #131. The docs can be viewed [here](https://github.com/simonmichael/hledger/blob/8d665ecc9f98c22ae8ec9a4db9f408c137877121/hledger/hledger_options.m4.md#valuation).

### CODE REVIEW

**Comment by alerque** [comment]
I'm brand new to the Ledger ecosystem and have just been importing various finances using hledger since last week. I came here after scrubbing the docs looking for just this feature! Thanks for your work on this (and the project in general). I'll be eager for it to land in a release.

**Comment by danielverdugo** [comment]
Great. The "-X" is long waited feature of mine.

@simonmichael Does it show the exchange rate effective on the date of transaction?

**Comment by simonmichael** [comment]
@danielverdugo, I like -X but so far I've always found -V was enough. Can you share a use case or two ? 

At one point it had a mode that used exchange rates on the date of each transaction, but it was complicated and I didn't have any clear use case for it. Currently it uses exchange rates at the end of each report subperiod instead. If you see a real-world need for it, please say more (and specify the desired report in detail).

**Comment by danielverdugo** [comment]
@simonmichael In my accounting system I use multiple currencies regularly. Primarily EUR and RUB. 

I use them in different occasions, both in Balance and Income statement accounts.

RUB is, unfortunately, not the stablest currency in the world, being the currency of the developing economy. So, many times I want to see my Balance or Income statement converted to other, more solid currencies, like EUR and USD.

More than that, with ledger I can use -X to track my investments.

I do it this way. For example, I have 10 stocks of Apple, Inc., which I bought for 199 USD each. I would record it as follows:
```
01-05 *
   Assets:Investments  10 AAPL
   Equity:Unrealised investment gain  -10 AAPL
   Equity:Unrealised investment gain  1990 USD
   Assets:Cash  -1990 USD
```

Now, just using the price directive (`P 2019-01-05 AAPL 210 USD`) I may monitor market vs. cost difference (in other words, unrealized investment gain) on the equity account using "-X USD".

I realize, my use cases may be rare. However, I find them quite handy.

**Comment by simonmichael** [comment]
> many times I want to see my Balance or Income statement converted to other, more solid currencies

Thanks @danielverdugo, that makes sense. While -V would convert to the currency you normally use, but you need -X for occasionally viewing in alternate currencies (without having to swap price files). 

> Now, just using the price directive (P 2019-01-05 AAPL 210 USD) I may monitor market vs. cost difference

-V seems enough for this one, but maybe it's a similar case to above. Thanks for the input.

**Pull request merged**
