### PR TITLE
Add rules example for the new YNAB Web csv export format

### PR DESCRIPTION
**Pull request by erplsf**
Was looking around examples and saw an outdated example for YNAB, decided to add a rules file that works for the latest export.

### CODE REVIEW

**Comment by simonmichael** [comment]
Great! Thanks for that. Does the outdated example need removing ?

Thanks for using `ci skip` - it should be no longer necessary, we are now using only Github CI and automatically ignoring doc commits.

**Comment by erplsf** [comment]
I'd leave it, as some people may still use YNAB 4, because it was a radical change in product, and some folks dislike new web version. But feel free to ditch it as there's enough examples of rules for csv files in there still.

**Comment by simonmichael** [comment]
Ok cool, let's keep both. The old one has a comment heading describing it, maybe you could add that to the new one to reduce confusion ?

**Comment by erplsf** [comment]
Sure, will see to it.

**Pull request merged**
