### PR TITLE
feat: CSV rule negation

### PR DESCRIPTION
**Pull request by bobobo1618**
I'm interested in hledger but really need https://github.com/simonmichael/hledger/issues/2054 for my use-case (certain locations for the same store fit in one purchase category, other locations in another).

I don't know a whole lot of Haskell but hopefully enough to make myself dangerous. I _think_ this change works? The tests I added seem to pass?

### CODE REVIEW

**Comment by simonmichael** [comment]
Sorry for the delay @bobobo1618 . A valuable feature! In my excitement I forgot to ask for documentation. Could you suggest some wording and I'll add it.

**Comment by bobobo1618** [comment]
I had a look at [the existing matcher documentation](https://hledger.org/1.31/hledger.html#matchers) and would suggest "When a matcher is preceded by an exclamation mark (`!`), the matcher will be negated; only lines that _don't_ match the original matcher will be matched."

**Comment by simonmichael** [comment]
Perfect. Thank you!

**Comment by simonmichael** [comment]
Howdy @bobobo1618 . I tried to use `!` in CSV rules for the first time, in an AND-ed condition, like this:
```
# stripe transfers where amount is positive
if STRIPE TRANSFER
& ! %amount -
```
but couldn't make it work. Would you have time to check this case and show a working example, or add a test and fix ?

**Comment by bobobo1618** [comment]
> Howdy @bobobo1618 . I tried to use `!` in CSV rules for the first time, in an AND-ed condition, like this:
> 
> ```
> # stripe transfers where amount is positive
> if STRIPE TRANSFER
> & ! %amount -
> ```
> 
> but couldn't make it work. Would you have time to check this case and show a working example, or add a test and fix ?

I'd love to but I'm afraid this is beyond my Haskell abilities. Right now the logic only supports a simple prefix but this feature would require some kind of recursive logical structure and I'm not familiar enough with how to make that work.

**Comment by simonmichael** [comment]
Mentioned this limitation in the manual for now.

**Pull request merged**
