### PR TITLE
Implement tidy csv output

### PR DESCRIPTION
**Pull request by Xitian9**
This introduces a new csv format which is useful for charting and further processing: [tidy csv](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html). Every row of the csv file consists of a single amount, and that row is indexed by the account name, the date, and the commodity. Here is an example:

```
$ hledger -f bcexample.hledger bal -TNY assets.*etrade -3 -O csv --layout=tidy
"account","date","commodity","value"
"Assets:US:ETrade","2012","GLD","0"
"Assets:US:ETrade","2012","ITOT","10.00"
"Assets:US:ETrade","2012","USD","337.18"
"Assets:US:ETrade","2012","VEA","12.00"
"Assets:US:ETrade","2012","VHT","106.00"
"Assets:US:ETrade","2013","GLD","70.00"
"Assets:US:ETrade","2013","ITOT","18.00"
"Assets:US:ETrade","2013","USD","-98.12"
"Assets:US:ETrade","2013","VEA","10.00"
"Assets:US:ETrade","2013","VHT","18.00"
"Assets:US:ETrade","2014","GLD","0"
"Assets:US:ETrade","2014","ITOT","-11.00"
"Assets:US:ETrade","2014","USD","4881.44"
"Assets:US:ETrade","2014","VEA","14.00"
"Assets:US:ETrade","2014","VHT","170.00"
"Assets:US:ETrade","Total","GLD","70.00"
"Assets:US:ETrade","Total","ITOT","17.00"
"Assets:US:ETrade","Total","USD","5120.50"
"Assets:US:ETrade","Total","VEA","36.00"
"Assets:US:ETrade","Total","VHT","294.00"
```

### CODE REVIEW

**Comment by Xitian9** [comment]
This is currently obtain using the option `--layout=tidy`, but I'm not sure this is the correct choice. Here is a review of the current layouts available.

## Text mode

### Wide output
```
Balance changes in 2012-01-01..2014-12-31:

                  ||                                          2012                                                     2013                                             2014 
==================++=========================================================================================================================================================
 Assets:US:ETrade || 10.00 ITOT, 337.18 USD, 12.00 VEA, 106.00 VHT  70.00 GLD, 18.00 ITOT, -98.12 USD, 10.00 VEA, 18.00 VHT  -11.00 ITOT, 4881.44 USD, 14.00 VEA, 170.00 VHT 
```

### Tall output
```
Balance changes in 2012-01-01..2014-12-31:

                  ||       2012        2013         2014 
==================++=====================================
 Assets:US:ETrade || 10.00 ITOT   70.00 GLD  -11.00 ITOT 
 Assets:US:ETrade || 337.18 USD  18.00 ITOT  4881.44 USD 
 Assets:US:ETrade ||  12.00 VEA  -98.12 USD    14.00 VEA 
 Assets:US:ETrade || 106.00 VHT   10.00 VEA   170.00 VHT 
 Assets:US:ETrade ||              18.00 VHT              
```

### Bare output
```
Balance changes in 2012-01-01..2014-12-31:

                  || Commodity    2012    2013     2014 
==================++====================================
 Assets:US:ETrade || GLD             0   70.00        0 
 Assets:US:ETrade || ITOT        10.00   18.00   -11.00 
 Assets:US:ETrade || USD        337.18  -98.12  4881.44 
 Assets:US:ETrade || VEA         12.00   10.00    14.00 
 Assets:US:ETrade || VHT        106.00   18.00   170.00 
```

## Csv mode

### Wide output
```
"account","2012","2013","2014"
"Assets:US:ETrade","10.00 ITOT, 337.18 USD, 12.00 VEA, 106.00 VHT","70.00 GLD, 18.00 ITOT, -98.12 USD, 10.00 VEA, 18.00 VHT","-11.00 ITOT, 4881.44 USD, 14.00 VEA, 170.00 VHT"
```

### Bare output
```
"account","commodity","2012","2013","2014"
"Assets:US:ETrade","GLD","0","70.00","0"
"Assets:US:ETrade","ITOT","10.00","18.00","-11.00"
"Assets:US:ETrade","USD","337.18","-98.12","4881.44"
"Assets:US:ETrade","VEA","12.00","10.00","14.00"
"Assets:US:ETrade","VHT","106.00","18.00","170.00"
```

### Tidy output
```
"account","date","commodity","value"
"Assets:US:ETrade","2012","GLD","0"
"Assets:US:ETrade","2012","ITOT","10.00"
"Assets:US:ETrade","2012","USD","337.18"
"Assets:US:ETrade","2012","VEA","12.00"
"Assets:US:ETrade","2012","VHT","106.00"
"Assets:US:ETrade","2013","GLD","70.00"
"Assets:US:ETrade","2013","ITOT","18.00"
"Assets:US:ETrade","2013","USD","-98.12"
"Assets:US:ETrade","2013","VEA","10.00"
"Assets:US:ETrade","2013","VHT","18.00"
"Assets:US:ETrade","2014","GLD","0"
"Assets:US:ETrade","2014","ITOT","-11.00"
"Assets:US:ETrade","2014","USD","4881.44"
"Assets:US:ETrade","2014","VEA","14.00"
"Assets:US:ETrade","2014","VHT","170.00"
```

## Layout options

As implemented, there are four arguments that `--layout` can take. Listed here is the current behaviour in this PR.

| Option | Text mode | Csv mode |
|----|--|----------------------------|
| `--layout=wide`  | wide  | wide |
| `--layout=tall`     | tall  | wide |
| `--layout=bare`  | bare | bare |
| `--layout=tidy`   | wide | tidy |

### Alternatives

1. As above, but have `--layout=tidy` be the same as `--layout=bare` in text mode.
2. `--layout=tall` in csv mode gives tidy output. This is maximally compact, and means there's a bijection from options to modes in each of text and csv modes, but its behaviour in text and csv modes is sufficiently different that it might be confusing.
3. Drop the bare csv mode and only implement tidy, which would replace csv bare mode.
   a. Leave the option as `--layout=bare`
   b. Rename the option `--layout=tidy`
4. Something else?

## Open questions

1. `--layout` doesn't have any effect in register, aregister, or print. Should it?
2. What about html mode?

**Comment by simonmichael** [comment]
Great examples.

I think all of this is in context of the balance command only ?

I think we need to be careful not to let --output-format and --layout overlap and complexify too much. I think we would be wise to consolidate and build out the options we currently provide before adding more.

I believe until now, only register and print reports show time on the y axis (ie, going down), while balance reports always show accounts on the y axis and time on the x axis (going across). The example of tidy output seems to be a hybrid with both accounts and time on the y axis. 

Why is there no tidy layout in text output, and no tall layout in csv output ? I assume considered not useful, still consistency could help reduce confusion. It would be useful to see examples of these as well.

**Comment by Xitian9** [comment]
> I think all of this is in context of the balance command only ?

Yes, correct. We should probably think about whether they make sense for register and aregister too. I think they don't make sense for print.
 
> I think we need to be careful not to let --output-format and --layout overlap and complexify too much. I think we would be wise to consolidate and build out the options we currently provide before adding more.

I agree, but it's a tricky balancing act. I definitely want others' opinions on the correct interface here. I put together this proposal so we would have something concrete to work off of.

> I believe until now, only register and print reports show time on the y axis (ie, going down), while balance reports always show accounts on the y axis and time on the x axis (going across).

Unless you call with `--transpose`.

> Why is there no tidy layout in text output, and no tall layout in csv output ? I assume considered not useful, still consistency could help reduce confusion. It would be useful to see examples of these as well.

Yes, a careful consideration of what to implement here is warranted. Here was my reasoning for the above.

`tall` is not implemented for csv mode because `tall` is basically a version of `bare` where commodities are split across multiple lines, but no effort is made to ensure the commodities in different columns match (e.g. ITOT is the first commodity in 2012 and GLD is the first commodity in 2013). This is helpful only in that it keeps the layout visually compact, which is not an important consideration for csv. The mixing of different commodities on the same line also makes computer parsing more difficult.

`tidy` is not implemented for text mode at this stage mostly because of laziness, but also because I'm not sure how useful it would be. The sole purpose of tidy output is that it makes the csv more easily parsable/extensible for computers. The combination of both accounts and time on the y-axis is confusing for humans to read, and makes reports very very long indeed (if you have `n` accounts and `t` time periods, tidy reports have `n * t` rows). I'm not sure anybody would prefer it, but I'm happy to hear other opinions.

**Comment by Xitian9** [comment]
Perhaps I should say that I think option 2 above (make tidy output accessible with `--layout=tall`, do not add `--layout=tidy`) seems perfectly acceptable to me, and is probably my preferred option. Although I do love @the-solipsist's suggested name `--layout=tidy`.

**Comment by simonmichael** [comment]
> tall is not implemented for csv mode because tall is basically a version of bare where commodities are split across multiple lines, but no effort is made to ensure the commodities in different columns match (e.g. ITOT is the first commodity in 2012 and GLD is the first commodity in 2013). This is helpful only in that it keeps the layout visually compact, which is not an important consideration for csv. The mixing of different commodities on the same line also makes computer parsing more difficult.

I wonder why we even need `tall` mode for terminal output.  Did we have a case where the extra compactness (compared to `bare`) justified it ?

Remind me again, why `bare` isn't sufficient for machine-readable csv ?

**Comment by Xitian9** [comment]
Many visualisation libraries (e.g ggplot, Vega) require tidy output for
plotting. Without it implemented in n hledger, it would need to be
transformed to tidy format with an external scripting language, e.g pandas
in python or dplyr in R.

Tall format makes a lot of sense for my use case. My accounts are primarily
in one or two commodities, but I have a large number of other commodities
that appear once or twice due to trips. If they stick around, they make the
text reports a sea of zeros which is hard to read.

**Comment by simonmichael** [comment]
> Many visualisation libraries (e.g ggplot, Vega) require tidy output for
> plotting. Without it implemented in n hledger, it would need to be
> transformed to tidy format with an external scripting language, e.g pandas
> in python or dplyr in R.

Thanks for the "tidy" link: 
https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html.

> Tall format makes a lot of sense for my use case. My accounts are primarily
> in one or two commodities, but I have a large number of other commodities
> that appear once or twice due to trips. If they stick around, they make the
> text reports a sea of zeros which is hard to read.

Ok, great.

**Comment by simonmichael** [comment]
Merged and documented at https://hledger.org/dev/hledger.html#data-layout. This could arguably be either an output format or a --layout mode; we chose the latter for now, making --layout a more general "data layout" option. Thanks!

**Pull request merged**
