### PR TITLE
cli,ui: Include full binary name and git hash in program version.

### PR DESCRIPTION
**Pull request by Xitian9**
One possible solution to #1539.

### CODE REVIEW

**Comment by Xitian9** [comment]
Well I didn't notice it at the time, but it looks like this PR removes the `--version+` flag, which was undocumented and completely equivalent to `--version` otherwise. If you would prefer to maintain this flag, let me know and I can change this, either restoring it as equivalent to `--version`, or having it output this more detailed version information, and maintaining `--version` as the old behaviour.

**Comment by simonmichael** [comment]
More dependence on Template Haskell is always a problem for bleeding edge platforms (web assembly ?), but I think we can't avoid it entirely. Precise version output is something we have needed for along time, so +1 for this. But can you replace gitrev with https://hackage.haskell.org/package/githash ? I think it is the successor package, uploaded 2020 instead of 2017 and used by eg stack.

**Comment by simonmichael** [comment]
Old:

    hledger 1.21.99

New:

    hledger-1.21.99-mac-x86_64 f820f427b8dfdc99c53ddb7f3829411a2f741efd

The new info is all useful but I feel it could be formatted in a more readable way. I guess this is the standard format from gitrev. Maybe it'll be different in githash, and I don't know what would be ideal exactly, but some notes just for the record:

- The hyphenation obfuscates the name of the program/package a little bit.
- The hyphenation logic is unclear - why are all parts but the last hyphenated.
- The platform + architecture appears between the two parts of the version info, separating them.

**Comment by simonmichael** [comment]
How do other tools do it - a few random examples:
```
$ stack --version
Version 2.7.1, Git revision 8afe0c2932716b0441cf4440d6942c59568b6b19 x86_64 hpack-0.34.4

$ git --version
git version 2.30.2

$ curl --version
curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
Release-Date: 2019-03-27
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS GSS-API HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL UnixSockets

$ pandoc --version
pandoc 2.11.4
Compiled with pandoc-types 1.22, texmath 0.12.1, skylighting 0.10.2,
citeproc 0.3.0.7, ipynb 0.1.0.1
User data directory: /Users/simon/.local/share/pandoc or /Users/simon/.pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

$ brew --version
Homebrew 3.1.9
Homebrew/homebrew-core (git revision a589318ffa; last commit 2021-06-03)
Homebrew/homebrew-cask (git revision 497625d493; last commit 2021-06-02)

$ gh --version
gh version 1.10.3 (2021-05-21)
https://github.com/cli/cli/releases/tag/v1.10.3

$ rg --version
ripgrep 12.1.1
-SIMD -AVX (compiled)
```

**Comment by Xitian9** [comment]
I was just reusing the existing hyphenation logic that was implemented in hledger 12 years ago. I'm happy to change that to something with fewer hyphens.

**Comment by simonmichael** [comment]
Following stack's style, showing the full git hash, not trying to fit in one 80-character line:
```
hledger 1.21.99, git revision f820f427b8dfdc99c53ddb7f3829411a2f741efd, mac-x86_64
```
A little shorter, more jargony, but more likely to fit in one line:
```
hledger 1.21.99, git hash f820f427b8dfdc99c53ddb7f3829411a2f741efd, mac-x86_64
```

There's still room for improvement. If we always show the git hash, it's not clear whether it represents a release build or not. Except for the ".99" hint. I don't know how hard this would be, but would it be ideal to also show a count of commits since last release, like git describe ?
```
$ git describe
1.21-93-gf820f427b
```
Could we ultimately do without the .99 convention ? I suspect not, it'll still be needed to help stack/cabal know when to rebuild.


PS we should do this for hledger-web --version also.

**Comment by simonmichael** [comment]
PS: but porting to githash and implementing for hledger-web are the only merge blockers I'd say.

**Comment by simonmichael** [comment]
PPS gitrev/githash don't spell out exactly how they impact building, will it be more fragile - requiring git ? Not working on windows ? Not a blocker, but something we'll find out.

**Comment by Xitian9** [comment]
It looks like `gitHash` has `git describe` functionality built-in, but only since version 1.4, which is included in stackage versions since 15.7. This unfortunately means it's only supported by our `stack.yaml`, `stack8.8.yaml` and `stack9.0.yaml`. This leaves `stack8.6.yaml` which we still support which doesn't have it.

**Comment by simonmichael** [comment]
I see "WARNING: None of this will work in a git repository without any commits.". Will it break non git builds, eg folks doing "cabal/stack unpack hledger" to do a quick fix ? Maybe we'd want to automatically disable it rather than break the build.

**Comment by Xitian9** [comment]
I think `gitHash` includes two ways of getting this info: one which fails when not in a git environment, and one which returns an either. The second one sounds safer, but I'm not sure if that caveat about the git repository without any commits still holds.

**Comment by Xitian9** [comment]
Would you prefer returning the `git describe` info if we're using a new enough version of `gitHash`, and falling back to something like `hledger 1.21.99, git revision f820f427b8dfdc99c53ddb7f3829411a2f741efd, mac-x86_64` if we're not, or would you rather it be uniform?

**Comment by simonmichael** [comment]
> It looks like gitHash has git describe functionality built-in, but only since version 1.4, which is included in stackage versions since 15.7. This unfortunately means it's only supported by our stack.yaml, stack8.8.yaml and stack9.0.yaml. This leaves stack8.6.yaml which we still support which doesn't have it.
> 

Ok, we can punt on describe for now (or use it only when new enough githash is detected..)

I have forgotten which GHCs we officially support, do you remember ? According to hledger/package.yaml GHC 8.2 is the oldest. I should probably remove older stack*.yaml files..

**Comment by simonmichael** [comment]
> Would you prefer returning the git describe info if we're using a new enough version of gitHash, and falling back to something like hledger 1.21.99, git revision f820f427b8dfdc99c53ddb7f3829411a2f741efd, mac-x86_64 if we're not, or would you rather it be uniform?
> 

Reliable uniform behaviour is good, but in this case I vote it'd be harmless enough to show the extra info when we can.

**Comment by Xitian9** [comment]
Last word I heard on supported stack versions was here: https://github.com/simonmichael/hledger/issues/1514#issuecomment-835461657

**Comment by simonmichael** [comment]
Right! Thanks. So GHC 8.6 and up.

(AFK)

**Comment by Xitian9** [comment]
Changes made. The build failure is because `githash` is not present in the stackage used by `stack8.2.yaml`. We have dropped support for that, but it is still being tested in the CI.

**Comment by simonmichael** [comment]
Thank you! Merged.

**Comment by Xitian9** [comment]
I can confirm that this continues to successfully build outside of a git environment. In particular, nix does not fetch the `.git` directory when building, so I get the fallback version `hledger 1.21.99, linux-x86_64`. Maybe it's worth finding a solution which is more robust to build method, but I'm happy to leave this as is for now.

**Comment by simonmichael** [comment]
I have been updating CI. cli.test 1 and 2 pass locally, but are failing in CI due to this strange version output:
```
:hledger/test/cli/cli.test:1: [Failed]
198
Command:
199
hledger --version
200
Expected stdout: 
201
/^hledger [0-9]/
202
Got stdout:      
203
hledger eeb23c2, linux-x86_64
204

205
:hledger/test/cli/cli.test:2: [Failed]
206
Command:
207
hledger balance --version
208
Expected stdout: 
209
/^hledger [0-9]/
210
Got stdout:      
211
hledger eeb23c2, linux-x86_64
```

**Comment by Xitian9** [comment]
And maybe what version of git the CI runs with. This might be due to different `git describe` output on different platforms. In particular, one possibility is that CI uses special annotated tags internally, which might explain output like this.

**Comment by Xitian9** [comment]
Hmm, I think I see the issue. The output of `giDescribe` is actually not the content of `git describe`, but of `git describe --always`, where `--always:  shows uniquely abbreviated commit object as fallback`. Since it's reporting the git hash, it must be using this fallback. The documentation doesn't make it explicit in which cases it uses the fallback, but I'm guessing that the CI somehow does not fetch the full tag history. And so, being unable to locate an appropriate ancestor tag to prefix, it uses the fallback.

I'm not sure what the appropriate resolution here is, if this is indeed the problem. The simplest is probably just to drop those two tests. More complicated would be to make sure CI fetches all the information it needs so `git describe` doesn't use the fallback.

**Comment by Xitian9** [comment]
Perhaps relevant: https://github.com/empirical-soft/empirical-lang/issues/105

**Comment by simonmichael** [comment]
Ha ha, we considered a git checkout and a non git checkout, but not "unusual" git checkouts. Thanks, I'll fix our CI checkout or something.

**Comment by simonmichael** [comment]
Fixed by cloning the full repo history and tags on each CI run (instead of just the latest commit). That is a pretty slow operation on my laptop, but on a github runner seems to increase checkout time only from 1s to 7s.

**Comment by simonmichael** [comment]
I have removed the *1.21.99 tags from master - if you have these locally, please delete them, I think they are spurious.

**Comment by simonmichael** [comment]
More notes for possible future work:

git describe by default does not show a hash if you are at a tag. So if I tag 1.22 and immediately build it, --version looks like `hledger 1.22, mac-x86_64`. git describe's --long flag helps ensure the hash is shown, though the 0 patchlevel is ugly: `1.22-0-g03fe5df6b`. I don't know if githash supports --long yet. Another desirable git describe flag might be --dirty, for the truly paranoid.

**Comment by simonmichael** [comment]
https://github.com/snoyberg/githash/pull/21

**Pull request merged**
