### PR TITLE
lib: use native POSIX wcwidth

### PR DESCRIPTION
**Pull request by ony**
Fixes simonmichael/hledger#895

screenshot

### CODE REVIEW

**Comment by simonmichael** [comment]
Status: blocked on a wcwidth release (https://github.com/simonmichael/hledger/issues/895#issuecomment-430062476, https://github.com/solidsnack/wcwidth/issues/2).

**Comment by simonmichael** [comment]
(Ideally.. or, some other workaround eg #895's suggestions.)

**Comment by simonmichael** [comment]
I think we shouldn't depend on an unmaintained library.

**Comment by simonmichael** [comment]
Pinged: https://github.com/solidsnack/wcwidth/issues/2#issuecomment-511463245

**Comment by simonmichael** [comment]
Update: no change - wcwidth is fixed on github but still unreleased and maintainerless. What to do ?

**Comment by simonmichael** [comment]
@ony it seems not much code, shall we add it to hledger-lib ?

**Comment by simonmichael** [comment]
Correction, it's more code than I thought. And it looks like code that could use maintenance, forever. Ugh. What are your thoughts ? I'd like to close this issue/PR somehow.

**Comment by simonmichael** [comment]
We could also just add the missing emoji codes to our big case statement. Maybe that's the simple way to go ?

**Comment by ony** [comment]
So current approaches that I was able to find:

- [`pandoc` and `hledger` have own hand crafted mappings](https://www.stackage.org/haddock/lts-14.15/pandoc-2.7.3/Text-Pandoc-Pretty.html#v:charWidth)
- [`wcwidth` consults native](https://www.stackage.org/lts-14.15/package/wcwidth-0.0.2) `wcwidth` which is part of POSIX.1-2001 and POSIX.1-2008 as per Linux man. It also can generate Haskell native table.
-  [`neovim` generates table from Unicode files with Lua script](https://github.com/neovim/neovim/blob/master/src/nvim/generators/gen_unicode_tables.lua)
- [Rust version `unicode-rs` generates table with Python script](https://github.com/unicode-rs/unicode-width/blob/master/scripts/unicode.py)
- I think I saw

Maybe Haskell deserves to have own implementation independent of platform...

I.e. understand [how to interpret](http://www.unicode.org/reports/tr11/tr11-19.html) and [`EastAsianWidth.txt`](https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt) (at least it includes cheese and says it is wide).

**Comment by simonmichael** [comment]
Great research. I shared with #ghc but I doubt they have the bandwidth..

Still wondering what happens when you install wcwidth on windows.

**Comment by simonmichael** [comment]
Confirmed by @phadej: installing wcwidth-0.2 on windows fails (`.\Data\Char\WCWidth.o:fake:(.text+0x5a): undefined reference to `wcwidth'`), and installing wcwidth-master succeeds (almost: "needed to add {-# LANGUAGE CPP #-} to one file").

**Comment by simonmichael** [comment]
Closing this in favour of the more portable #1749.

**Pull request closed without merging**
