### PR TITLE
Upgrade to easytest 0.3.

### LINKED ISSUE #983: Build failure, seemingly wiht easytest 0.3
```
[12 of 49] Compiling Hledger.Utils.Test ( Hledger/Utils/Test.hs, dist/build/Hledger/Utils/Test.o )

Hledger/Utils/Test.hs:101:57: error:
    Not in scope: ‘E.ok’
    Module ‘EasyTest’ does not export ‘ok’.
    |
101 | expectEqPP expected actual = if expected == actual then E.ok else E.crash $
    |                                                         ^^^^

Hledger/Utils/Test.hs:114:9: error:
    Not in scope: ‘E.io’
    Module ‘EasyTest’ does not export ‘io’.
    |
114 |   ep <- E.io (runParserT (evalStateT (parser <* eof) mempty) "" input)
    |         ^^^^

Hledger/Utils/Test.hs:127:10: error:
    Not in scope: ‘E.io’
    Module ‘EasyTest’ does not export ‘io’.
    |
127 |   eep <- E.io $ runExceptT $
    |          ^^^^

Hledger/Utils/Test.hs:143:9: error:
    Not in scope: ‘E.io’
    Module ‘EasyTest’ does not export ‘io’.
    |
143 |   ep <- E.io (runParserT (evalStateT parser mempty) "" input)
    |         ^^^^

Hledger/Utils/Test.hs:160:10: error:
    Not in scope: ‘E.io’
    Module ‘EasyTest’ does not export ‘io’.
    |
160 |   eep <- E.io $ runExceptT $ runParserT (evalStateT parser mempty) filepath input
    |          ^^^^
```

### PR DESCRIPTION
**Pull request by joelburget**
Fixes #983

### CODE REVIEW

**Comment by simonmichael** [comment]
Thanks a lot @joelburget. If you're working on the build failure let me know, otherwise happy to take it from here. But could you possibly re-push this without all the trailing whitespace changes ?

**Comment by joelburget** [comment]
I just cleaned up the whitespace changes and (hopefully) the build failure as well

**Comment by simonmichael** [comment]
Thanks @joelburget ! With the easytest rewrite and the switch to hedgehog there's quite a lot to digest here. I see that the hedgehog runner prints more progress output (best viewed in a proper terminal), and that all skipped tests are reported as "gave up after 1 discard, passed 0 tests", in yellow, which looks a little too alarming. I expect I can customise that though.

**Comment by simonmichael** [comment]
My old comparison helpers pretty printed the compared values and showed a call stack. Both are quite helpful.. would it make sense to have === do something like that ?

**Comment by simonmichael** [comment]
Actually recheckSeed hardcodes hedgehog's RunnerConfig. Access to that config would be useful I think.

**Comment by simonmichael** [comment]
Also, I guess we need to require easytest >=0.3 in all the package.yaml files. (Or use CPP to support both old and new easytest, but hopefully requiring easytest 0.3+ will be fine for old GHC versions too.)

**Comment by simonmichael** [comment]
PS if you don't get back to this I'll work on it at some point. My priorities are 1. the lower bounds 2. less verbose test runner output (I use the test command to run a single test quite a lot when developing) 3. print the location of failing tests 4. pretty-print compared values from failing tests.

**Comment by simonmichael** [comment]
Hi @joelburget, any thoughts on the comments above ? I'd like to move to newer easytest and unblock easytest in stackage. I have rebased this branch against latest master (and bumped the package deps), can force push it to your branch if you make me a collaborator there or can push it to a temp branch.

**Comment by simonmichael** [comment]
To expand on:

> all skipped tests are reported as "gave up after 1 discard, passed 0 tests"
> ...
> I use the test command to run a single test quite a lot

I often do eg `make ghcid-test-Hledger.Data.AccountName.expandAccountNames` to watch the results of one test; now that shows a verbose "gave up after 1 discard" for every test, making it less useful. I'd like to make skipped tests silent somehow.

**Comment by simonmichael** [comment]
Rebase pushed to https://github.com/simonmichael/hledger/tree/joelburget-master .

**Comment by simonmichael** [comment]
We have moved to tasty for ghc 8.8/mainstream support. Thanks anyway @joelburget.

**Pull request closed without merging**
