### PR TITLE
Remove partial record accessors in hledger-ui

### PR DESCRIPTION
**Pull request by mitchellwrosen**
#358

### CODE REVIEW

**Comment by simonmichael** [comment]
Interesting! It feels like we are now handling screens with tongs. And no more partial functions. Does it prevent construction of nonsensical values ?

I imagine we can find ways to clean it up further, eg sInit/sDraw/sHandle don't use their first argument.

And Screen is still a closed/monolithic type of course. I wonder how we could reduce the amount of screen-specific knowledge there, confining that more to the screen modules. Do you think there's some other sane solution based on typeclasses that we haven't found yet ?

**Comment by mitchellwrosen** [comment]
I do think there are other ways of cleaning this interface up, yeah, but I think the biggest wins would involve untangling `Screen` from `UIState`. So instead of

```haskell
sInit :: Screen -> Day -> Bool -> UIState -> UIState
```
it might be
```haskell
sInit :: Day -> Bool -> Screen
```
(passing in whatever pieces of `UIState` are necessary, like maybe `UIOpts`).

I'm a bit confused about why it's called `init` if there is already an existing screen inside the `UIState` passed into `sInit`, though.

Then, it may make sense to parameterize `UIState` by the current screen, so as to avoid the partial pattern matches in `sInit`, `sDraw`, `sHandle`.

But, I'm not totally familiar with the code, and am just taking baby steps at the moment :)

This particular patch just gets rid of the partial functions at the cost of some wrapping/unwrapping.

**Comment by mitchellwrosen** [comment]
Ah I see what you mean about `sInit`/`sDraw`/`sHandle` not using their first argument. I didn't even notice. It's because before they were record accessors, but they always operated on the screen in the given UIState.

**Comment by simonmichael** [comment]
"init" is not a great name. It's called to update the screen's data model state (eg the list of items to show) on entering the screen but also whenever needed, eg when the filter is changed or the file is reloaded. (It is not called for the smallest UI state changes, like moving the selection.) I didn't call it "update" because in game loops that is called on every tick, but perhaps update or [re]generate or something else would be better than init.

**Comment by simonmichael** [comment]
@mitchellwrosen: looking at this PR today, it doesn't seem to remove the "init function called with wrong screen type, should not happen" error calls. I'm confused, wasn't that the purpose of removing partial record accessors ?

**Comment by mitchellwrosen** [comment]
@simonmichael That would require a more significant refactoring - I believe you would need to parameterize `UIState` by the screen it's showing. This is just restructuring the monolithic ADT with partial record accessors into separate types

**Comment by simonmichael** [comment]
Ok, one year is long enough! I'm rejecting this one. Let's hold out for another cleanup with more compelling benefits.

**Pull request closed without merging**
