### PR TITLE
dev: Use strict maps instead of lazy maps. Since we generally use all

### PR DESCRIPTION
**Pull request by Xitian9**
the values, this results in a very small performance speedup, and
otherwise no changes.

### CODE REVIEW

**Comment by simonmichael** [comment]
Hmm, there's also "If you don't care about ordering, consider use Data.HashMap.Strict from the [unordered-containers](https://hackage.haskell.org/package/unordered-containers) package instead."

**Comment by Xitian9** [comment]
Yes. I tested using a strict HashMap for some of the fields in `Journal`, and it resulted in an ambiguous improvement: memory usage went down a tiny bit, and time went up a tiny bit. I could do a more thorough test if you'd prefer, but it looked like marginal gains if any for our use case.

**Comment by simonmichael** [comment]
Cool. And also, aeson switched away from Data.HashMap because certain data can make it O(n^2), apparently.

Map.Strict looks a bit ambiguous here for some reason, in this test (notice the consistent slowdown with the largest file):
```
~/src/hledger$ BENCHEXES=hledger,hledger-1827 make bench

run quick performance benchmarks in bench.sh (approximate, can be skewed):
Running 5 tests 1 times with 2 executables at 2022-02-06 14:27:43 HST:

Best times:
+----------------------------------------------------++---------+--------------+
|                                                    || hledger | hledger-1827 |
+====================================================++=========+==============+
| -f examples/10000x1000x10.journal print            ||    0.55 |         0.61 |
| -f examples/10000x1000x10.journal register         ||   10.15 |         9.15 |
| -f examples/10000x1000x10.journal balance          ||    0.47 |         0.46 |
| -f examples/1000x1000x10.journal balance --weekly  ||    1.18 |         0.92 |
| -f examples/10000x1000x10.journal balance --weekly ||   12.73 |        16.29 |
+----------------------------------------------------++---------+--------------+
cat bench.sh >bench 
chmod a+x bench
~/src/hledger$ BENCHEXES=hledger,hledger-1827 make bench

run quick performance benchmarks in bench.sh (approximate, can be skewed):
Running 5 tests 1 times with 2 executables at 2022-02-06 14:29:09 HST:

Best times:
+----------------------------------------------------++---------+--------------+
|                                                    || hledger | hledger-1827 |
+====================================================++=========+==============+
| -f examples/10000x1000x10.journal print            ||    0.65 |         0.54 |
| -f examples/10000x1000x10.journal register         ||   10.42 |         9.31 |
| -f examples/10000x1000x10.journal balance          ||    0.50 |         0.45 |
| -f examples/1000x1000x10.journal balance --weekly  ||    1.30 |         1.00 |
| -f examples/10000x1000x10.journal balance --weekly ||   12.18 |        17.75 |
+----------------------------------------------------++---------+--------------+
cat bench.sh >bench 
chmod a+x bench
~/src/hledger$ BENCHEXES=hledger,hledger-1827 make bench

run quick performance benchmarks in bench.sh (approximate, can be skewed):
Running 5 tests 1 times with 2 executables at 2022-02-06 14:30:16 HST:

Best times:
+----------------------------------------------------++---------+--------------+
|                                                    || hledger | hledger-1827 |
+====================================================++=========+==============+
| -f examples/10000x1000x10.journal print            ||    0.61 |         0.53 |
| -f examples/10000x1000x10.journal register         ||    9.68 |         9.01 |
| -f examples/10000x1000x10.journal balance          ||    0.47 |         0.44 |
| -f examples/1000x1000x10.journal balance --weekly  ||    1.08 |         0.90 |
| -f examples/10000x1000x10.journal balance --weekly ||   10.58 |        15.58 |
+----------------------------------------------------++---------+--------------+
cat bench.sh >bench 
chmod a+x bench
```

**Comment by Xitian9** [comment]
Since this is ambiguous, and only a small benefit if any, let's leave it for now and save our brain power.

**Pull request closed without merging**
