### PR TITLE
Update journal.md

### PR DESCRIPTION
**Pull request by cnicolai**
The link to the ledger wiki on pointed to an "new wiki entry site".
The entry apparently has been renamed.

This is my very first PR on any repo, so please make sure I didn't make a mistake :)
Thanks for the great work!

### CODE REVIEW

**Comment by efx** [comment]
Awesome, thanks for the catch @cnicolai. Changes looks good to me.

**Comment by cnicolai** [comment]
Alright, thank you!
And 1.5 was the right place to change it?

**Comment by simonmichael** [comment]
What @efx said. Thanks @cnicolai and welcome to the project.

You changed it in the 1.5 docs snapshot, which is good; that will update http://hledger.org/doc/1.5/journal.html . Would you mind also  changing it in the latest (dev) docs, at hledger-lib/hledger_journal.m4.md.

**Comment by cnicolai** [comment]
@simonmichael 
Sure, my pleasure.

**Pull request merged**
