### PR TITLE
Add balancing amounts in periodic transactions before applying auto postings

### PR DESCRIPTION
**Pull request by Xitian9**
Addresses #1412.

The second commit here is a minimal fix for the problem. The first was work I did while trying to understand where the problem is.

<s>I actually think that generating the forecast transactions should happen in journal finalisation, not as a separate step after the journal has already been finalised.</s> This would avoid having to re-balance the whole journal several times.

### CODE REVIEW

**Comment by simonmichael** [comment]
journalTransform: can you add to the haddock some details of the error case - what can cause this to fail.

journalAddForecast: the old haddock says "...will raise an error". Is that still true ? Can the new code both raise a (program terminating) error,  and return an error message ? Let's add a mention of the error message case to the haddock here also.

**Comment by Xitian9** [comment]
> journalTransform: can you add to the haddock some details of the error case - what can cause this to fail.

Added.

> journalAddForecast: the old haddock says "...will raise an error". Is that still true ?

No, that is not. I have updated the haddock.

**Comment by simonmichael** [comment]
Thanks!

Not a problem for this PR, but is your new style:
```
return $ journalTransform opts =<< files
```
better than the old one ?
```
return $ journalTransform opts <$> files
```
The old one is quite common around the codebase, and to me it's easier to understand here (a chain of $-ish, versus a more complicated mixture of operators..

**Comment by Xitian9** [comment]
> Not a problem for this PR, but is your new style:
> ```
> return $ journalTransform opts =<< files
> ```
> better than the old one ?
> ```
> return $ journalTransform opts <$> files
> ```

It's better in the sense that it works. That `return` is to lift into the `IO` monad, and `files` is of type `Either String Journal`. On the other hand,  the type of `journalTransform opts` has changed from `Journal -> Journal` to `Journal -> Either String Journal`. We therefore need monadic bind (`>>=` or its flipped version `=<<`) instead of `fmap`

**Comment by simonmichael** [comment]
Ah of course, thanks.

I forgot I had some small questions about:

```
lib!: modifyTransactions now takes a Map of commodity styles, and will  …
style amounts according to that argument. journalAddForecast and
journalTransform now return an Either String Journal.

This improves efficiency, as we no longer have to restyle all amounts in
the journal after generating auto postings or periodic transactions.
Changing the return type of journalAddForecast and journalTransform
reduces partiality.
```

Just curious, this means a change in user functionality ? Users will see the standard styles applied where they weren't before, in.. auto posting amounts ? Inferred balancing amounts involving auto postings ?

And "improves efficiency" here is in "in principle", not "measured and noticeable in normal usage" I assume.

**Comment by Xitian9** [comment]
> ```
> lib!: modifyTransactions now takes a Map of commodity styles, and will  …
> style amounts according to that argument. journalAddForecast and
> journalTransform now return an Either String Journal.
> 
> This improves efficiency, as we no longer have to restyle all amounts in
> the journal after generating auto postings or periodic transactions.
> Changing the return type of journalAddForecast and journalTransform
> reduces partiality.
> ```
> 
> Just curious, this means a change in user functionality ? Users will see the standard styles applied where they weren't before, in.. auto posting amounts ? Inferred balancing amounts involving auto postings ?

No change in user behaviour. In every case where these functions were used before, the default styles were applied afterwards by manually calling the function and iterating over the whole journal. Now this is done as part of generating the new postings/transactions, and doesn't need to be done separately. (Which also means it is only done for the new transactions, and not the whole journal.)
 
> And "improves efficiency" here is in "in principle", not "measured and noticeable in normal usage" I assume.

Well, I haven't tested, but I presume so. The main objective here was not to speed things up, but to avoid errors where you forget to re-style the journal.

**Comment by simonmichael** [comment]
Lovely!

**Pull request merged**
