### PR TITLE
Preserve implicit amounts and prices the way user wrote them in output of print command

### PR DESCRIPTION
**Pull request by ony**
See discussion in #442 .
Summary:
- By default `hledger print` do not inject inferred amounts into an output. I.e. keeps balance assignments and transaction balancing postings as is. Also, it doesn't put inferred prices to balance transaction.
- With `hledger print --explicit` we can get the same be haviour we had before this change.

### CODE REVIEW

**Comment by simonmichael** [comment]
Nice. I'm going to test this one locally for a bit too. We'll need to mention this in the print docs in the manual.

**Comment by peti** [comment]
One remaining issue is that `EUR 0` gets re-written to `0`. It's probably not a big deal, but IMHO there's an undesirable loss of information. `USD 0` and `EUR 0` are two different things and I'd prefer for `hledger` to distinguish between the two.

**Comment by ony** [comment]
@peti C++ `ledger` also shows only `0`. Looks like both works the same. I'll look into that probably after playing with `hledger rewrite` in hope to resolve #99 some day.

**Comment by peti** [comment]
> C++ `ledger` also shows only 0.

Yes, it does. Still, I think that behavior sucks, especially when the currency is dropped from balance assertions.

**Comment by peti** [comment]
OK, I played around with the new code quite a bit and it works great. I didn't encounter any problems (other than that `EUR 0` thing).

**Comment by simonmichael** [comment]
> Also, it doesn't put inferred prices to balance transaction.

Is this change required for this issue ? Does it not change some reports ?

**Comment by ony** [comment]
@simonmichael , only `print` report affected. I've moved related changes to `Print.hs`. I.e. `showTransaction` is not affected. You can bring back inferred prices with `print --explicit`.
My intention was to keep changes of original input as minimal as possible as long as it doesn't affect interpretation. In the case of inferred prices all needed information already there.

**Comment by simonmichael** [comment]
Thanks for the testing @peti. 0, EUR 0, USD 0 etc. are different internally (this is used by hledger-web's register chart, eg). I don't recall if the cli commands expose that though. Can you paste a minimal example ?

**Comment by peti** [comment]
~~~~
$ cat test.ledger 
2017/01/13 Test
    Foo         EUR 0 = EUR 0
    Bar         USD 0 = USD 0
$ hledger -f test.ledger print
2017/01/13 Test
    Foo             0 = 0
    Bar             0 = 0
~~~~

**Comment by peti** [comment]
This is what it looks like from within `ghci`:

~~~
λ> nulltransaction { tpostings = [nullposting { pamount = mixed [eur 0]}] } 
0000/01/01
                 0
~~~

**Comment by simonmichael** [comment]
Thanks, yes I see now. Commodified zero was added for hledger-web, but all cli commands and probably other tools still treat zero as commodityless, following the original Ledger style. This isn't print-specific and may be a lot of work, let's not tackle it in this issue.

**Comment by ony** [comment]
```diff
--- a/hledger-lib/Hledger/Data/Amount.hs
+++ b/hledger-lib/Hledger/Data/Amount.hs
@@ -258,7 +258,7 @@ showPriceDebug (TotalPrice pa) = " @@ " ++ showAmountDebug pa
 -- zero are converted to just \"0\". The special "missing" amount is
 -- displayed as the empty string.
 showAmount :: Amount -> String
-showAmount = showAmountHelper False
+showAmount = showAmountHelper True
 
 showAmountHelper :: Bool -> Amount -> String
 showAmountHelper _ Amount{acommodity="AUTO"} = ""
```

But 19 tests fails (not only `print` related).
Maybe someday there will be a `PrintStyle` that is passed through all `showTransaction` and down.

**Pull request merged**
