### PR TITLE
Allow yesod-form 1.7

### PR DESCRIPTION
**Pull request by felixonmars**
Builds fine and all tests pass here.

### CODE REVIEW

**Comment by juhp** [comment]
Could you please do a revision on Hackage or a new release of hledger-web?

This is blocking yesod-form-1.7 for Stackage Nightly: commercialhaskell/stackage#5983

**Comment by simonmichael** [comment]
I have published a revision - let me know of any problem.

**Comment by juhp** [comment]
Thanks Simon!

I am still trying to work out why stackage can't see your revision yet somehow.
Maybe it will work tomorrow if the hackage cache gets updated.

**Comment by simonmichael** [comment]
@juhp, I wonder if https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml#L6614 (no-revisions) is biting here ? It was to prevent some badness which I don't remember entirely, related to:

> Revision 1 was good for cabal installers with old GHC, but bad for
> stackage nightly. This should fix the latter. I might continue this
> policy - use revisions to patch up the cabal install experience,
> but avoid them in stackage.

If you want to remove the hledger entries there, I'm ok with it.

**Comment by juhp** [comment]
Thanks, good catch!

**Pull request merged**
