### PR TITLE
Upstream Sandstorm build files

### PR DESCRIPTION
**Pull request by ocdtrekkie**
Changes to the files needed to build for Sandstorm haven't been made yet, but I wanted to open this PR while I had real success at actually grabbing all of these commits. The submodule thing gave me all sorts of pain, I had to remove it before I could even try the merge. After much suffering, I am afraid anything more I do will break this.

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
@simonmichael Still trying to make it actually work. Details in #425.

Usually the .sandstorm is in the root of a project. I presume one could modify it to back out of the hledger-web directory for the things out there. Let me see if I can get it working first, then I'll see if I can move it and it still work?

**Comment by simonmichael** [comment]
Cool. I won't do any merging until things have settled.

**Comment by ocdtrekkie** [comment]
Useful notes on things this contains outside general metadata:

- Vagrantfile: Specifies the parameters of the VM we're building the app in
- global-setup.sh: Builds the VM for packaging Sandstorm apps (generally-speaking)
- setup.sh: Sets up any prerequisite software to packaging a given app
- build.sh: Runs any build steps to create the release files of the app
- launcher.sh: Script that's called on app load to launch the packaged app

**Comment by ocdtrekkie** [comment]
Still not done: Trying to move .sandstorm directory inside hledger-web and then fix building it after that. I'd like to get an updated release out before I monkey with that since it's building.

**Comment by simonmichael** [comment]
> Useful notes on things this contains outside general metadata:
> 

Good, feel free to add these somewhere they will be seen if useful. (.sandstorm/README ?)

**Comment by ocdtrekkie** [comment]
@simonmichael I'll probably do some sort of readme, so that Sandstorm build instructions are present in the .sandstorm directory.

**Comment by ocdtrekkie** [comment]
So, I am reading the vagrant-spk code, and I don't think it's possible to move /.sandstorm into hledger-web because we need other files/directories outside of hledger-web. vagrant-spk is strictly designed to place the app files in /opt/app in the virtual machine, and run scripts out of /opt/app/.sandstorm. If we could "just" operate out of the hledger-web folder it wouldn't be an issue.

So the way I see it, there are potentially two decent options:
- If you're okay with it, /.sandstorm could live in the repo's root.
- We could maybe merge this into a `sandstorm` branch instead of master, but still keep it in the same repository.

**Comment by simonmichael** [comment]
Ok, no problem to leave in root. Should it be renamed to sandstorm or something ? Seems to deserve more than a dot name.

**Comment by ocdtrekkie** [comment]
/.sandstorm is where it explicitly wants to be. (On an application with a lot more platform scripts it makes more sense, I think: https://github.com/RocketChat/Rocket.Chat/ You can see .docker, .openshift, etc. here)

I'd say go ahead and merge it for now (as this represents the published state of the app anyways), I'll open a new PR when I assemble screenshots, build instructions, etc.

**Comment by ocdtrekkie** [comment]
I didn't break the build, did I? o_o

**Comment by simonmichael** [comment]
Huh.. no. It failed the first time with a spurious-looking error so I cleared the Travis cache and restarted the build. Now I see it has failed in a different way, I'll investigate.

**Comment by simonmichael** [comment]
Success with travis at last. Thanks!

**Pull request merged**
