### PR TITLE
Use hpack in hledger-ui

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by simonmichael** [comment]
Looks good, let's do it!

I'll probably keep the description where it was, it's easier to refill when editing.

**Comment by simonmichael** [comment]
Oh ignore my comment, I won't be editing it there any more. Great.

**Comment by simonmichael** [comment]
With hpack 0.14.0 installed, I keep getting "hledger-ui.cabal was generated with a newer version of hpack, please upgrade and try again." from stack build - any tips ?

**Comment by mitchellwrosen** [comment]
That might mean upgrade stack? ("stack upgrade")

**Comment by simonmichael** [comment]
Good call, thanks.

**Pull request merged**
