### PR TITLE
JPY separators

### PR DESCRIPTION
**Pull request by Ekleog**
OK so I've taken a first stab at doing #796.

However, there's something I don't get about unit tests: in my second commit I added a clearly-wrong test (with a willingly changed digit), and yet `stack --nix test` doesn't fail (though I had to locally reset the `stack.yml` snapshot to `[…]-15` instead of `-25` in order to remove the need for ghc8.4.2, but I guess this shouldn't matter much).

From my reading of https://github.com/simonmichael/hledger/wiki/Developer-workflows it should however have been tested and failed (at least the place where I've added the test looks very much like a unit test), so I'm not sure what I'm doing wrong in the adding-a-test or the testing procedure?

Disclaimer: I'm not used to haskell development, and even though I did a few toy projects with it, I still don't really grok how the toolchain actually works.

### CODE REVIEW

**Comment by simonmichael** [comment]
It looks like some bit-rot in the tests, I don't believe TESTS is defined any more.

The travis test failed because of the warning about the unused jpy definition. `make travistest` is a little better at finding things that will fail on travis.

**Comment by simonmichael** [comment]
PS, thanks for diving in!

I haven't understood the above docs in detail; how would you explain 1兆2,345億6,789万0,123円 to westerners ? Is there some way to simulate how it would sound when read aloud ?

FYI the code until now assumes one digit group separator in all numbers. And it's probably about to assume the same digit group separator among all numbers in a file (see #793). Your changes so far should allow numbers to be parsed, but the style won't be preserved in the output.

**Comment by Ekleog** [comment]
> I haven't understood the above docs in detail; how would you explain 1兆2,345億6,789万0,123円 to westerners ? Is there some way to simulate how it would sound when read aloud ?

Hmm, so I'm not japanese, so I can't positively assert anything, only learning the language and about to go for a quite long period over there :)

First, 1兆2,345億6,789万0,123円 is 1234567890123円 : the kanji are only used for grouping. Grouping is done by 4-digits, as is done in pronunciation, and commas are put at thousands, because otherwise it'd be written １兆２千３百４十５億６千７百８十９万百２十３円 for correct pronunciation, which is waaaay too long.

> Can any of those three characters appear at the start or end of a number ? The current code might parse them as commodity symbols in that case.

Then, I'm almost sure numbers can't *start* with a digit grouping: even though for 十, 百 or 千 (10, 100 and 1000) they can be used without a preliminary number, 万, 億 and 兆 (1,0000 , 1,0000,0000 and 1,0000,0000,0000) are always used with a preceding 1 when they are used.

However, I guess they *can* appear at the end of digits: １万円 is 10,000¥. So I guess I've got some more work to do here.

> FYI the code until now assumes one digit group separator in all numbers. And it's probably about to assume the same digit group separator among all numbers in a file (see #793). Your changes so far should allow numbers to be parsed, but the style won't be preserved in the output.

Hmm, I'm not sure about that? I already have
```ledger
commodity €
    format 1.000,00€
commodity $
    format $1,000.00
```
in my ledger file, and output is alright, with both € and $ in the right display format.

So somehow it already manages to do the right thing. I'll have to look into how to make it handle multiple digit separators, I was sure indian rupees quoted in the docs had mixed dots and commas, but it turns out I was wrong.

Thanks for the pointer!

> It looks like some bit-rot in the tests, I don't believe TESTS is defined any more.
> 
> The travis test failed because of the warning about the unused jpy definition. make travistest is a little better at finding things that will fail on travis.

Hmm… I'm going to try and fix the tests, then, thanks!

**Comment by Ekleog** [comment]
Well, I don't understand at all the errors `stack --nix test` now gives me, as when I try to perform type inference in my head I really believe this *should* type… I guess I'm reaching my limits of Haskell knowledge here, so depending on your answer I'll likely stop trying to unbreak these tests, and just put my added test somewhere else.

Anyway, thank you already for your first feedback!

**Comment by simonmichael** [comment]
Thanks for the info. Investigating the disabled tests would be welcome, but it's probably best handled as a separate task.

**Comment by Ekleog** [comment]
OK, so upon more reading it looks like it'll require a complete refactoring of the parser, around `rawnumberp` [(here)](https://github.com/Ekleog/hledger/blob/4606759edd6c40394b90a6b5a6f1100192005d5f/hledger-lib/Hledger/Read/Common.hs#L749) especially, as the current return type doesn't allow to model multiple digit group separators.

So I unfortunately won't have time to do this in the near future, leaving the PR open in case someone else comes along and wants to know what's to be done. I'll try to get back to it as soon as possible, but don't expect better than a few months at best :/

**Comment by simonmichael** [comment]
Understandable. Thanks for the prototyping.

**Pull request closed without merging**
