### PR TITLE
A fix for a bug with the -H option. It did not show anything when a period with no transactions was chosen rather than show the ending balances.

### PR DESCRIPTION
**Pull request by nniro**
These set of patches add a testing context for the fix and the fix itself.
The testing context is to make sure the fix does in fact behave like it should. They were added for BalanceReport and MultiBalanceReport only.

this is an excerp of one of the patches description :

This patch fixes a bug that happened when using the -H option on
a period without any transaction. Previously, the behavior was no output
at all even though it should have shown the previous ending balances of
past transactions. (This is similar to previously using -H with -E, but
with the extra advantage of not showing empty accounts)

### CODE REVIEW

**Comment by nniro** [comment]
Ah I didn't notice the warnings that samplejournal2 is already initialized elsewhere in the project. I'll need someone to tell me where to put the new samplejournal (or just rename it to samplejournal3). At first, I wanted to update samplejournal with my new entry and then change all the tests that failed to reflect the new journal, but I wasn't sure if that would be accepted or what.

**Comment by simonmichael** [comment]
Status check ? I think you're still working on this and I don't need to do anything at the moment.

**Comment by nniro** [comment]
Finally got travis happy.

**Comment by simonmichael** [comment]
I see examples/sample.journal hasn't been changed. We have both samplejournal and sample.journal because unit tests needed a pure value, functional tests needed a file. Until now they have been the same, for simplicity and ease of moving tests between unit and functional. I would probably keep it that way, unless you think it's fine to let them diverge ? If so maybe we should rename one of them, samplejournal -> testjournal or something.

Re unit tests vs functional tests: I did find it quite hard to understand/replicate/test this after being away from it; functional tests would have helped me process it more quickly. But unit tests run faster and more focussed, and we should probably try them some more, so I'm fine with them.

**Comment by simonmichael** [comment]
I have rebased and merged. Thanks for the fix, and good catch! I wonder how long it has been undetected.

**Pull request closed without merging**
