### PR TITLE
Improve efficiency of PostingsReport when called with many intervals

### LINKED ISSUE #1683: prevent excessive memory usage
# Or: Don't let a typo hang user's machine

Eduardo reported in chat:

> I have made a typo in a transaction. The year was 20211 instead of 2021. Later, I tried to generate a balance report with --daily. My CPU and memory usage went to the roof and my computer didn't freeze because I stopped it soon. Can we consider this a bug or only a user error?

We must consider it both I think - it's not very good if it's this easy to hang your machine with hledger. Here are some tasks that come to mind:

1. Reproduce and study (quantify) this case
2. Search for and catalog other ways to cause the same result
3. Optimise them so they perform well enough (& decide what that means), if possible
4. As a fallback, try to detect operations likely to exceed available memory/acceptable resource usage and fail with an explanation ? (Process no more than 1m transactions per 1G system ram, or similar ? There could also be an interactive warning prompt, but we don't like these by default..)
5. Allow this to be overridden with a --no-memory-check flag.

Any thoughts ?

### PR DESCRIPTION
**Pull request by Xitian9**
Fixes #1683, maybe?

When accidentally called with a large number of intervals, PostingsReport is very inefficient (complexity looks to be `O(p*i)`, where `i` is the number of intervals and `p` is the number of postings. This improves this to `O(p*log(i))`, where `i` is the number of intervals which actually have postings in them (or all intervals if called with `--empty`).

This also improves the efficiency of `splitSpan`, requiring about half as many date calculations.

### CODE REVIEW

**Comment by la-wu** [comment]
In https://github.com/simonmichael/hledger/pull/1685/files#diff-0d9c798b1335019b9475e284450700481b3ce00c8f416523a5f73e83badcc112R186-R187 are we relying on GHC lifting / inlining the `latestSpanContaining colspans` computation (https://github.com/simonmichael/hledger/blob/master/hledger-lib/Hledger/Data/Dates.hs#L344) to avoid `O(i log i)` work per posting?

**Comment by Xitian9** [comment]
Yes, we are. I think this is a pretty reliable one, but it's probably worth profiling to make sure it's actually doing it.

**Comment by Xitian9** [comment]
Here are the profiling numbers:

```
$ cat typo.j
2021-01-01 Test
    (assets)  1

2021-01-02 Test
    (assets)  1

2021-01-03 Test
    (assets)  1

2021-01-04 Test
    (assets)  1

20211-01-01 Test2
    (assets)  2
```

Command: `stack exec --profile -- hledger -f typo.j register -D +RTS -p 2>/dev/null`

master:
```
	   hledger +RTS -p -RTS -f typo.j register -D

	total time  =        4.27 secs   (4267 ticks @ 1000 us, 1 processor)
	total alloc = 12,819,064,456 bytes  (excludes profiling overheads)

COST CENTRE                                MODULE                         SRC                                                 %time %alloc

postingDate                                Hledger.Data.Posting           Hledger/Data/Posting.hs:(208,1)-(209,55)             13.3   24.9
splitspan'                                 Hledger.Data.Dates             Hledger/Data/Dates.hs:(247,1)-(252,57)               12.2   24.0
postingDate.dates                          Hledger.Data.Posting           Hledger/Data/Posting.hs:209:11-55                    11.5   10.4
isPostingInDateSpan'                       Hledger.Data.Posting           Hledger/Data/Posting.hs:(252,1)-(253,72)              9.7    7.0
applyN                                     Hledger.Utils                  Hledger/Utils.hs:(142,1)-(143,43)                     8.9   14.9
spanContainsDate                           Hledger.Data.Dates             Hledger/Data/Dates.hs:(266,1)-(269,65)                7.1    0.0
summarisePostingsByInterval.postingsinspan Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:180:5-60            5.8    1.7
summarisePostingsInDateSpan                Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:(195,1)-(213,64)    5.3    5.0
tdate                                      Hledger.Data.Types             Hledger/Data/Types.hs:398:7-11                        4.6    0.0
splitspan'.subs                            Hledger.Data.Dates             Hledger/Data/Dates.hs:250:11-24                       4.3    0.0
nextday                                    Hledger.Data.Dates             Hledger/Data/Dates.hs:521:1-19                        3.9    1.7
nubSortBy                                  Data.List.Extra                src/Data/List/Extra.hs:(764,1)-(767,19)               2.5    3.7
pdate                                      Hledger.Data.Types             Hledger/Data/Types.hs:348:7-11                        1.9    0.0
summarisePostingsByInterval                Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:(177,1)-(180,60)    1.8    2.9
summarisePostingsInDateSpan.anames         Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:207:5-38            1.5    1.2
summarisePostingsByInterval.summarisespan  Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:179:5-90            1.4    0.0
nubSort                                    Data.List.Extra                src/Data/List/Extra.hs:752:1-27                       1.1    0.0
summarisePostingsInDateSpan.summarypes     Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:206:5-132           1.1    0.8
summarisePostingsInDateSpan.summaryps      Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:(204,5)-(205,96)    0.8    1.7
```

prtraverse:
```
	   hledger +RTS -p -RTS -f typo.j register -D

	total time  =        1.15 secs   (1152 ticks @ 1000 us, 1 processor)
	total alloc = 4,793,412,424 bytes  (excludes profiling overheads)

COST CENTRE                  MODULE             SRC                                     %time %alloc

latestSpanContaining.spanSet Hledger.Data.Dates Hledger/Data/Dates.hs:341:5-65           25.5   17.7
splitspan.intervalStarts     Hledger.Data.Dates Hledger/Data/Dates.hs:(238,5)-(240,54)   17.2   26.6
startsToSpans                Hledger.Data.Dates Hledger/Data/Dates.hs:(245,1)-(249,31)   16.6   15.5
startsToSpans.datespans      Hledger.Data.Dates Hledger/Data/Dates.hs:248:5-63           15.2   31.0
splitSpan.\                  Hledger.Data.Dates Hledger/Data/Dates.hs:210:69-93          13.3    8.9
<                            Hledger.Data.Types Hledger/Data/Types.hs:75:63-65            4.3    0.0
>=                           Hledger.Data.Types Hledger/Data/Types.hs:75:63-65            4.1    0.0
isEmptySpan                  Hledger.Data.Dates Hledger/Data/Dates.hs:(258,1)-(259,48)    3.0    0.0

…

             latestSpanContaining                                                     Hledger.Data.Dates                                 Hledger/Data/Dates.hs:(331,1)-(341,65)                                   54175           1    0.0    0.0    36.8   17.7
              latestSpanContaining.go                                                 Hledger.Data.Dates                                 Hledger/Data/Dates.hs:(333,5)-(339,57)                                   54176           5    0.0    0.0     0.0    0.0
               <=                                                                     Hledger.Data.Types                                 Hledger/Data/Types.hs:75:63-65                                           54192         110    0.0    0.0     0.0    0.0
                <                                                                     Hledger.Data.Types                                 Hledger/Data/Types.hs:75:63-65                                           54193         110    0.0    0.0     0.0    0.0
               latestSpanContaining.go.supSpan                                        Hledger.Data.Dates                                 Hledger/Data/Dates.hs:339:9-57                                           54177           5    0.0    0.0     0.0    0.0
               spanContainsDate                                                       Hledger.Data.Dates                                 Hledger/Data/Dates.hs:(263,1)-(266,65)                                   54203           5    0.0    0.0     0.0    0.0
              latestSpanContaining.spanSet                                            Hledger.Data.Dates                                 Hledger/Data/Dates.hs:341:5-65                                           54178           1   25.5   17.7    36.8   17.7
               isEmptySpan                                                            Hledger.Data.Dates                                 Hledger/Data/Dates.hs:(258,1)-(259,48)                                   54189     6643761    3.0    0.0     3.0    0.0
               >=                                                                     Hledger.Data.Types                                 Hledger/Data/Types.hs:75:63-65                                           54190     6643760    4.1    0.0     8.3    0.0
                <                                                                     Hledger.Data.Types                                 Hledger/Data/Types.hs:75:63-65                                           54191     6643760    4.3    0.0     4.3    0.0
```

My reading of this is that `spanSet` in `latestSpanContaining` is being called only once, and the comparison operators within it are being called 6 643 760 times: exactly the number of days between the start and end of the journal. This is as expected, I believe.

**Comment by simonmichael** [comment]
Profiles look great. I'm curious about the max residencies and `+RTS -s` generally, if you still have the executables handy.

I haven't understood the GHC lifting case in detail, but haskell software has been known to regress in performance when optimisation rules fired differently in a new GHC version. Could we do something to force the optimisation so we can be sure ?

**Comment by Xitian9** [comment]
I think in this case it's just a matter of making sure not to bind the variable `ps`. This is occasionally very awkward, but in this case it's just a matter of pulling a binding in the where clause out. I'll add another commit.

**Comment by Xitian9** [comment]
Hmm… max residencies don't look as good.

master:

```
  21,117,314,432 bytes allocated in the heap
      17,691,024 bytes copied during GC
         292,488 bytes maximum residency (3 sample(s))
          31,480 bytes maximum slop
               5 MiB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     20331 colls,     0 par    0.044s   0.047s     0.0000s    0.0004s
  Gen  1         3 colls,     0 par    0.006s   0.006s     0.0019s    0.0039s

  TASKS: 4 (1 bound, 3 peak workers (3 total), using -N1)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.001s  (  0.001s elapsed)
  MUT     time    4.583s  (  4.576s elapsed)
  GC      time    0.050s  (  0.053s elapsed)
  RP      time    0.000s  (  0.000s elapsed)
  PROF    time    0.000s  (  0.000s elapsed)
  EXIT    time    0.000s  (  0.001s elapsed)
  Total   time    4.635s  (  4.630s elapsed)

  Alloc rate    4,607,426,702 bytes per MUT second

  Productivity  98.9% of total user, 98.8% of total elapsed
```

new prtraverse: (`-p` profiling is almost exactly the same)

```
   7,776,627,448 bytes allocated in the heap
   7,787,618,160 bytes copied during GC
     948,711,768 bytes maximum residency (16 sample(s))
       3,169,680 bytes maximum slop
            2198 MiB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0      7475 colls,     0 par    1.118s   1.120s     0.0001s    0.0007s
  Gen  1        16 colls,     0 par    1.568s   1.568s     0.0980s    0.3887s

  TASKS: 4 (1 bound, 3 peak workers (3 total), using -N1)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.001s  (  0.001s elapsed)
  MUT     time    1.185s  (  1.175s elapsed)
  GC      time    2.686s  (  2.688s elapsed)
  RP      time    0.000s  (  0.000s elapsed)
  PROF    time    0.000s  (  0.000s elapsed)
  EXIT    time    0.000s  (  0.001s elapsed)
  Total   time    3.873s  (  3.865s elapsed)

  Alloc rate    6,563,422,564 bytes per MUT second

  Productivity  30.6% of total user, 30.4% of total elapsed
```

**Comment by Xitian9** [comment]
Well, I found another solution which is strictly better than master in all ways, but takes a bit longer and has more allocations overall than the solution here. Let me know your opinion.

```
	   hledger +RTS -p -s -RTS -f typo.j register -D

	total time  =        1.88 secs   (1877 ticks @ 1000 us, 1 processor)
	total alloc = 7,450,908,688 bytes  (excludes profiling overheads)

COST CENTRE                                     MODULE                         SRC                                                 %time %alloc

summarisePostingsByInterval.groupByCols         Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:(185,5)-(189,86)   15.0   15.7
summarisePostingsInDateSpan                     Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:(210,1)-(228,64)   13.1    8.6
splitspan.intervalStarts                        Hledger.Data.Dates             Hledger/Data/Dates.hs:(238,5)-(240,54)               10.5   17.1
startsToSpans                                   Hledger.Data.Dates             Hledger/Data/Dates.hs:(245,1)-(249,31)               10.4   10.0
startsToSpans.datespans                         Hledger.Data.Dates             Hledger/Data/Dates.hs:248:5-63                        9.4   20.0
summarisePostingsByInterval.groupByCols.(...)   Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:189:9-86            9.2    5.0
splitSpan.\                                     Hledger.Data.Dates             Hledger/Data/Dates.hs:210:69-93                       8.4    5.7
nubSortBy                                       Data.List.Extra                src/Data/List/Extra.hs:(764,1)-(767,19)               6.0    6.4
summarisePostingsByInterval                     Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:(178,1)-(195,37)    3.5    5.0
summarisePostingsInDateSpan.anames              Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:222:5-38            3.1    2.1
summarisePostingsInDateSpan.summarypes          Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:221:5-132           2.4    1.4
summarisePostingsInDateSpan.summaryps           Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:(219,5)-(220,96)    1.9    2.9
summarisePostingsByInterval.\                   Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:179:27-88           1.8    0.0
nubSort                                         Data.List.Extra                src/Data/List/Extra.hs:752:1-27                       1.6    0.0
summarisePostingsByInterval.groupByCols.matches Hledger.Reports.PostingsReport Hledger/Reports/PostingsReport.hs:189:9-86            1.4    0.0
```

```
  12,134,839,064 bytes allocated in the heap
      12,451,464 bytes copied during GC
         292,488 bytes maximum residency (3 sample(s))
          31,480 bytes maximum slop
               5 MiB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0     11778 colls,     0 par    0.026s   0.028s     0.0000s    0.0004s
  Gen  1         3 colls,     0 par    0.006s   0.006s     0.0020s    0.0040s

  TASKS: 4 (1 bound, 3 peak workers (3 total), using -N1)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.001s  (  0.001s elapsed)
  MUT     time    1.962s  (  1.958s elapsed)
  GC      time    0.032s  (  0.033s elapsed)
  RP      time    0.000s  (  0.000s elapsed)
  PROF    time    0.000s  (  0.000s elapsed)
  EXIT    time    0.000s  (  0.001s elapsed)
  Total   time    1.996s  (  1.994s elapsed)

  Alloc rate    6,183,875,112 bytes per MUT second

  Productivity  98.3% of total user, 98.2% of total elapsed
```

**Comment by Xitian9** [comment]
So the current situation is that we have two possible fixes, let's call them v1 and v2.

v1 is a better solution than master in all metrics except maximum residency, where it is significantly worse than master (2.2GiB  versus 5MiB for the typo example).

v2 is better than master in all metrics, including having the same maximum residency as master.

Comparing v1 and v2 is a bit tricky, but here are my notes for the journal `typo.j`:
- `-p` profiling reports less time and fewer total allocation for v1 over v2 (1.15s and 4.8GiB versus 1.88s and 7.5GiB)
- `-s` profiling reports less time and maximum residency memory for v2 over v1 `2.00s total and 292kB max versus 3.87s and 949MB max)

When run on a more normal journal (my journal with weekly reporting), the performance of all three option is basically the same, with minor differences in speed and memory usage roughly in line with what you see in `typo.j`.

My interpretation is that v2 is probably the best option. I'll switch this PR over, but if you disagree I can change it back.

**Comment by la-wu** [comment]
For my edification since I'm not very adept at first-principle guessing where Haskell memory allocations / optimizations come in... it seems like

- v1 residency is high because we must cache the intermediate set in `latestSpanContaining` while we iterate over postings for the performance improvement
- master and v2 don't suffer from this because they look at each posting / colspan relatively serially

Does that sound correct?

In either case I agree v2 is better (since a slightly more egregious typo of another digit would cause a significant memory bottleneck even on a modern machine)

**Comment by Xitian9** [comment]
> For my edification since I'm not very adept at first-principle guessing where Haskell memory allocations / optimizations come in... it seems like
> 
>     * v1 residency is high because we must cache the intermediate set in `latestSpanContaining` while we iterate over postings for the performance improvement
> 
>     * master and v2 don't suffer from this because they look at each posting / colspan relatively serially
> 
> Does that sound correct?

Yes, that is correct.

**Comment by Xitian9** [comment]
We've been getting some conflicting profiling numbers, so I'll put together my results here. If we can reproduce that's great. If we can find the problem, that's also great.

```
$ cat typo.j
2021-01-01 Test
    (assets)  1

2021-01-02 Test
    (assets)  1

2021-01-03 Test
    (assets)  1

2021-01-04 Test
    (assets)  1

20211-01-01 Test2
    (assets)  2
```

Tests were generated with the following command:
```
for end in {2300,2400,3000,5000,10000,20000,25000}; do
    for bin in hledger-{master,prtraverse}; do
        echo $bin $end > $bin-$end.txt
        ./$bin reg -f typo.j -e $end -D +RTS -s >/dev/null 2>> $bin-$end.txt
    done
done
```

Results are in the attached file. [summary.txt](https://github.com/simonmichael/hledger/files/7177015/summary.txt)

**Comment by simonmichael** [comment]
Reproduced here. Much better, thanks!

**Pull request merged**
