### PR TITLE
Adding "--value"/"-V" option for balancesheet/incomestatement/cashflow and register

### PR DESCRIPTION
**Pull request by mstksg**
Let me know if this is in the spirit of the library/utility! :)

I tried my best to adhere to the style that I saw used across the library, but feel free to tell me if there are any stylistic inconsistencies!

I see some potential for refactoring out balancesheet/incomestatement/cashflow commands, too, and would be willing to do it if you think that it'd be helpful to do so.

### CODE REVIEW

**Comment by mstksg** [comment]
hm, just realized that it'd make a lot more sense to just "market value-ize" the entire journal itself before anything happens, instead of the reports.

**Comment by simonmichael** [comment]
Great! Can you also update the manual for these commands - cf "Market value" section in hledger/doc/commands-balance.m4.md.

You could be right about the ordering. I found it harder to convince myself it would be correct and better that way. I'm not totally clear on how to decide what order things should be done in. If you try it, be sure to run the tests.

By all means do refactor these commands. As you know they're just a thin layer above the balance command, and arguably should be some kind of alias rather than a full command. Do you find them useful with -V ? One way or another, it would be nice to bring them to feature parity with the balance command, eg by basing them on multiBalanceReport.

**Comment by mstksg** [comment]
I find -V useful because I track assets with lots of different currencies and commodities, and the summaries can be a bit unweildy because each balance and transaction can take several lines :)  -V lets me see things as one-line/one-amount aggregates

**Comment by simonmichael** [comment]
Sometimes `-B` is enough for that, but it's not the same as -V I know. There's also `cur:CURRENCY` to see them one at a time.

**Comment by simonmichael** [comment]
Also, the balance command can be configured to show multi-commodity amounts on one line.. just throwing out ideas.

**Comment by mstksg** [comment]
@simonmichael oh, what is that configuration option? :O

**Comment by simonmichael** [comment]
http://hledger.org/hledger.html#custom-balance-output

**Comment by simonmichael** [comment]
@mstksg were you going to refactor this, and add docs ? If it's done similarly to the balance command, I don't mind if it's not optimally factored. Releasing 1.1 soon, I can update the docs if you prefer.

**Comment by simonmichael** [comment]
It seems I may not have time to update this for HEAD today - please do it if you can.

**Comment by simonmichael** [comment]
This didn't make 1.1 as I have no more hacking time today. I regret this, my apologies.

**Comment by mstksg** [comment]
No problem!  I've been out of town for the holidays.  I'll probably get some time to finish this up for the next release when I get back, thank you for your patience :)

**Pull request merged**
