### PR TITLE
--budget switch for balance + --show-unbudgeted

### PR DESCRIPTION
**Pull request by adept**
Attempt to create "real amount vs budgeted amount" side-by-side view

Discussion is in PR #644

### CODE REVIEW

**Comment by adept** [comment]
Hmm... I really dont understand what to do about Tavis error here. I added Decimal to hledger.cabal, and redoing all the "stack build..." invocations work for me locally.

**Comment by simonmichael** [comment]
@adept I guess you need to add it to package.yaml as well. The cabal file is generated from that.

**Comment by adept** [comment]
Indeed. Fixed.

**Comment by simonmichael** [comment]
Screenshot ? (A paste showing this in action would be helpful)

**Comment by adept** [comment]
@simonmichael i have tutorial/howto here: 9c7f97cb6aa797dd54abba7547a93aabf81e5906

**Comment by simonmichael** [comment]
Superseded by #654.

**Pull request closed without merging**
