### PR TITLE
lib: Include price directives when calculating journal end date.

### PR DESCRIPTION
**Pull request by Xitian9**
Addresses #1405.

Let me know what you think of these changes.

### CODE REVIEW

**Comment by simonmichael** [comment]
This seems like a reasonably useful change of default behaviour, and there's probably no need to make it a new function or dependent on a new argument. 

https://hledger.org/hledger.html#report-start-end-date says:
> Most hledger reports show the full span of time represented by the journal data, by default. So, the effective report start and end dates will be the earliest and latest transaction or posting dates found in the journal.

I guess the new doc will be something like:
> By default, most hledger reports will show the full span of time represented by the journal data, as follows: the default report start date will be the earliest transaction or posting date, and the default report end date will be the latest transaction, posting, or market price date.

**Comment by Xitian9** [comment]
New docs added.

**Comment by simonmichael** [comment]
Thanks!

**Comment by Xitian9** [comment]
Actually, I've just noticed a few bugs with this implementation, and I'm not 100% clear where they're coming from. I have some fixes in mind (which also address #1396), but I need to make sure there are not more bugs being swept under the carpet.

**Comment by adept** [comment]
If you have multiple yearly files, and they all include common prices.journal, then this change would mean that the end date for all reports generated from any of these yearly files becomes the date of the ast price. This looks rather weird if your last price is "yesterday" and you are generating a report for 3 years ago.

I guess I should just reorganize my files, and move prices into the yearly journals. 

Just raising the visibility of this as you probably want to mention this in the changelog.

**Comment by Xitian9** [comment]
I don't have much to say on this subject. My journals are not separated by year, so whenever I need to limit to a specific timeframe I use `-b/-e` options. I'm happy to defer to others about what works best in their workflow.

If we were wanting to make the changes @simonmichael suggests, we might even be able to limit it further. transactions + prices could be limited to just when using `--value=end`, as the other forms are independent of report end date.

An internal question: currently the journal end date is the latest of the transaction and price dates. Making this change would suggest that the journal end date should always be the latest of the transaction dates, which is then modified in certain circumstances. This would restore the output of `journalDateSpan` to its previous behaviour, perhaps good for compatibility.

**Comment by simonmichael** [comment]
>  we might even be able to limit it further. transactions + prices could be limited to just when using --value=end, as the other forms are independent of report end date.

True. I guess the question is, what will be least surprising and most intuitive and easy to explain.

**Comment by simonmichael** [comment]
Resolved as @Xitian9 suggested by #1495. Now only end-valued (`--value-end`) reports pick last transaction or market price date as default report end date. Other reports pick just last transaction date, as before.

**Pull request merged**
